const accomodations = {
    'pavilion hotel kuala lumpur': {
        category: "accomodation",
        link_name: "pavilion hotel kuala lumpur",
        name: "Pavilion Hotel Kuala Lumpur",
        image: "/pavilion-hotel.jpg",
        room_info: "Stylish Rooms, 24-Hours Concierge, Multiple Dining Options, Spa & Fitness",
        payment_info: "RM200/person",
        short_location: "Kuala Lumpur",
        location: "14 Jalan Pinang, Kuala Lumpur 50450 Malaysia",
        location_link: "https://www.google.com/maps/dir/3.1166212,101.6364583/170,+Jalan+Bukit+Bintang,+55100+Kuala+Lumpur,+Wilayah+Persekutuan+Kuala+Lumpur/@3.1287088,101.6362397,13z/data=!3m1!4b1!4m9!4m8!1m1!4e1!1m5!1m1!1s0x31cc362b89754727:0x5e25d8fab7273d14!2m2!1d101.7148486!2d3.1486329?entry=ttu&g_ep=EgoyMDI1MDUyOC4wIKXMDSoASAFQAw%3D%3D",
        price: 89,
        favourite: false,
        rating: 4.7,
        official_website: "https://www.banyantree.com/malaysia/pavilion-hotel",
        description: "Offering city view and free WiFi, Pavilion Hotel Kuala Lumpur provides luxurious accomodations conveniently located in the city. With elegant dining options, a world-class spa, and modern meeting facilities, it is the perfect destination for both business and leisure travelers.",
        detail: "Infinity pool overlooking the skyline, Sky Gym, exclusive Club Lounge, and direct access to Pavilion Mall via skybridge. Member rates from ~USD110 ≈ RM520/night (with breakfast); Check-in 3:00 PM, Check-out 12:00 PM. Best weekdays during low seasons (Feb–Apr, Sep–Nov) for lowest rates; flash sales around 11.11 & Black Friday. Request high-floor city view; covered walkway to KLCC takes ~15 mins; Club Lounge afternoon tea is great value."
    },

    'shangri-la kuala lumpur': {
        category: "accomodation",
        link_name: "shangri-la kuala lumpur",
        name: "Shangri-La Kuala Lumpur",
        image: "/shangri-la-kl.jpg",
        room_info: "Blackout curtains, High Speed Internet (WiFi), Airport transportation, Pool, Spa & Fitness",
        payment_info: "RM289/person",
        short_location: "Kuala Lumpur",
        location: "11 Jalan Sultan Ismail, Kuala Lumpur 50250 Malaysia",
        location_link: "https://www.google.com/maps/dir//11,+Jln+Sultan+Ismail,+Kuala+Lumpur,+50250+Kuala+Lumpur,+Wilayah+Persekutuan+Kuala+Lumpur/@3.154074,101.6239383,12z/data=!4m8!4m7!1m0!1m5!1m1!1s0x31cc482a7b0c105f:0xe4d2b948624de950!2m2!1d101.7063403!2d3.1540773?entry=ttu&g_ep=EgoyMDI1MDUyOC4wIKXMDSoASAFQAw%3D%3D",
        price: 289,
        favourite: false,
        rating: 4.8,
        official_website: "https://www.shangri-la.com/kualalumpur/shangrila/",
        description: "A traditional greeting from the heart awaits each of our guests on arrival to the Shangri-La Hotel, Kuala Lumpur. Our hotel is a welcome retreat from the bustling streets of the city; relax poolside in our tropical gardens, re-connect over drinks in our sun drenched lounge or rejuvenate and recharge at our Health Club & SPA.",
        detail: "Tropical garden pool in the city, 6 restaurants (Lemon Garden buffet is the most popular), and private Horizon Club access. Shangri-La Circle member rate with breakfast from ~USD110; 15% off for 30-day advance booking. Best December for festive decor & lobster buffet (rates higher); weekday lunch buffets offer great value. Request a garden wing high floor; app allows room selection and mobile key access."
    },

    'sunway resort hotel': {
        category: "accomodation",
        link_name: "sunway resort hotel",
        name: "Sunway Resort Hotel",
        image: "/sunway-resort-hotel-spa.jpg",
        room_info: "Blackout curtains, High Speed Internet (WiFi), Airport transportation, Pool, Spa & Fitness",
        payment_info: "RM300/person",
        short_location: "Selangor",
        location: "1, Persiaran Lagoon, Bandar Sunway, 47500 Petaling Jaya, Selangor",
        location_link: "https://www.google.com/maps/dir//1,+Persiaran+Lagoon,+Bandar+Sunway,+47500+Petaling+Jaya,+Selangor/@3.1195136,101.6266752,12z/data=!4m8!4m7!1m0!1m5!1m1!1s0x31cc4c812c0a18cb:0x96bc62906ec10444!2m2!1d101.6087575!2d3.071118?entry=ttu&g_ep=EgoyMDI1MDUyOC4wIKXMDSoASAFQAw%3D%3D",
        price: 300,
        favourite: false,
        rating: 4.9,
        official_website: "https://www.sunwayhotels.com/sunway-resort",
        description: "Sunway Resort Hotel, formerly Sunway Resort Hotel & Spa, is Kuala Lumpur's most iconic 5-star hotel, located in Sunway City Kuala Lumpur—Malaysia's premier entertainment and hospitality destination. The hotel features 477 smart, environmentally friendly rooms and suites, designed and equipped with state-of-the-art technology. Specialty suites cater to business travellers, families, wellness seekers and luxury enthusiasts. Guests can enjoy exclusive lounges, family-friendly zones like Waterventure and extraordinary dining—from the world-class Gordon Ramsay Bar & Grill, the chef's first restaurant in Malaysia and outside London, to laid-back poolside dining at Sunset Terrace.",
        detail: "Fully refurbished 477 smart rooms, direct access to Sunway Lagoon theme parks, and Malaysia's first Gordon Ramsay Bar & Grill. Family Terrace from ~RM900/night; look for 'Room + Theme Park' bundled packages on official site. Best to avoid Malaysian/Singapore school holidays (June–August & November–December). For families, book WaterVenture floor; register kids in advance for the Wonderland Explorers Club."
    },

    'one world hotel': {
        category: "accomodation",
        link_name: "one world hotel",
        name: "One World Hotel",
        image: "/one-world-hotel.jpg",
        room_info: "Blackout curtains, High Speed Internet (WiFi), Airport transportation, Pool, Spa & Fitness",
        payment_info: "RM300/person",
        short_location: "Selangor",
        location: "First Avenue Bandar Utama City Centre, Petaling Jaya 47800 Malaysia",
        location_link: "https://www.google.com/maps/dir//City+Centre,+First+Avenue,+Lebuh+Bandar+Utama,+Bandar+Utama,+47800+Petaling+Jaya,+Selangor/@3.1473955,101.5347482,12z/data=!4m8!4m7!1m0!1m5!1m1!1s0x31cc492b58970a77:0x2d3fe930d5bb6ad7!2m2!1d101.6171502!2d3.1473987?entry=ttu&g_ep=EgoyMDI1MDUyOC4wIKXMDSoASAFQAw%3D%3D",
        price: 300,
        favourite: false,
        rating: 4.6,
        official_website: "https://www.tripadvisor.com.my/Commerce?p=TABAIndependentHotels&src=0&geo=656672&from=Hotel_Review&area=&slot=2&matchID=1&oos=0&cnt=1&silo=30356&bucket=875171&nrank=1&crank=1&clt=CLD&tm=328875077&managed=false&capped=false&gosox=5_3Y6UYwwGjgw_c7hEwIkaMWncZYqB1tN1tJAU3Ybs1UzJsHmO1A0W8n_IVX36vvypxiViMSB6kUDmyTXVRwVQ&bapid=2&cs=1f4b94b941584f8bca73aeb6ca214b52f&ba_uid=df55e2d0-d067-4579-b3a6-156f28c4adad",
        description: "The award-winning 5-star One World Hotel, Petaling Jaya features 6 categories of 452 contemporary guestrooms and suites furnished with luxurious amenities, facilities and services. Conveniently adjoined to the world's 7th largest mall, 1 Utama comprises of more than 650 retail outlets, with direct access to the Bandar Utama MRT Station and just minutes away from downtown Kuala Lumpur and the Kuala Lumpur International Airport. ",
        detail: "Connected to 1 Utama (7th largest mall in the world), direct MRT access, saltwater pool, and 4 restaurants. Deluxe room with breakfast from ~RM480; free parking for guests. Best July anniversary sale or 11.11 shopping festivals; lower rates on weekdays. Zuan Yuan Chinese restaurant is highly rated; use skybridge to MRT to save on transport."
    },

    'swiss garden resort kuantan': {
        category: "accomodation",
        link_name: "swiss garden resort kuantan",
        name: "Swiss Garden Resort Kuantan",
        image: "/swiss-garden-resort.jpg",
        room_info: "Blackout curtains, High Speed Internet (WiFi), Airport transportation, Pool, Spa & Fitness",
        payment_info: "RM280/person",
        short_location: "Pahang",
        location: "2656-2657 Jln Kuantan - Kemaman, Kuantan 26100 Malaysia",
        location_link: "https://www.google.com/maps?gs_lcrp=EgZjaHJvbWUqCggAEAAY4wIYgAQyCggAEAAY4wIYgAQyFggBEC4YrwEYxwEYgAQYmAUYmgUYngUyBwgCEAAYgAQyBwgDEAAYgAQyDAgEEAAYFBiHAhiABDIICAUQABgWGB4yCAgGEAAYFhgeMgYIBxBFGDzSAQgxMTc4ajBqN6gCALACAA&um=1&ie=UTF-8&fb=1&gl=my&sa=X&geocode=KTf1Jg11sMgxMTInBrGEU9A1&daddr=2656~2657,+Mukim+Balok+Beach+Beserah+26100,+Kuantan,+Pahang",
        price: 280,
        favourite: false,
        rating: 4.7,
        official_website: "https://www.swissgarden.com/beach-resort-kuantan/",
        description: "Sky, sea and sun provide a peaceful backdrop to a landscape so alluring it stirs the emotions. The vivid colours of nature's palette glow in the soft tropical light accenting the purity of air, water and land. From the colors of the sunset, to soothing air greeting you with a warm embrace; the family and kids friendly Swiss- Garden Beach Resort, Kuantan, offers sensual delights at every turn with a beautiful beach front, fun and enjoyable kids club as well as a fun-filled splash pool perfect for family staycation.",
        detail: "Private beachfront, dual swimming pools, Kids Club & splash pool, and 3 dining venues. Renovated Deluxe Room with breakfast from ~RM330; Family Rooms fit up to 4 guests. Best dry season (March–October) with calm seas; weekends attract local families. Book 'Sea-Facing' wing for best views; bring insect repellent for evenings on the beach."
    },

    'hyatt regency resort kuantan': {
        category: "accomodation",
        link_name: "hyatt regency resort kuantan",
        name: "Hyatt Regency Resort Kuantan",
        image: "/hyatt-regency-kuantan.jpg",
        room_info: "Blackout curtains, High Speed Internet (WiFi), Airport transportation, Pool, Spa & Fitness",
        payment_info: "RM190/person",
        short_location: "Pahang",
        location: "Teluk Cempedak, Kuantan 25050 Malaysia",
        location_link: "https://www.google.com/maps/dir/3.9154832,103.4159196/Teluk+Cempedak,+25050+Kuantan,+25050+Pahang/@3.8730095,103.2830537,12z/data=!4m8!4m7!1m0!1m5!1m1!1s0x31c8a54547faa933:0x339d68da41de1544!2m2!1d103.3712922!2d3.8113542?entry=ttu&g_ep=EgoyMDI1MDUyOC4wIKXMDSoASAFQAw%3D%3D",
        price: 190,
        favourite: false,
        rating: 4.9,
        official_website: "https://www.hyatt.com/hyatt-regency/en-US/kuakt-hyatt-regency-kuantan-resort?src=corp_lclb_google_seo_kuakt&utm_source=google&utm_medium=organic&utm_campaign=lmr",
        description: "Located on the stunning beachfront of Teluk Cempedak, on the east coast of peninsular Malaysia and within proximity to Kuantan city, capital of Pahang, the refurbished Hyatt Regency Kuantan Resort is the perfect place for making meaningful connections that last a lifetime. 301 guestrooms and suites that have been completely rebuilt, including new family oriented rooms",
        detail: "Seafront resort at Teluk Cempedak, two lagoon-style pools, Beach Bar, and Camp Hyatt activities. Member rate with breakfast from ~RM450; sea view rooms ~RM80 extra. Best April–September offers clearer skies and sunrise views; avoid monsoon season (Nov–Jan). High-floor sea view rooms offer the best experience; 5-min walk to Teluk Cempedak's food stalls and beach."
    },

    'hard rock hotel desaru': {
        category: "accomodation",
        link_name: "hard rock hotel desaru",
        name: "Hard Rock Hotel Desaru",
        image: "/hard-rock-hotel-desaru.jpg",
        room_info: "Blackout curtains, High Speed Internet (WiFi), Airport transportation, Pool, Spa & Fitness",
        payment_info: "RM159/person",
        short_location: "Johor",
        location: "Jalan Pantai 3, Bandar Penawar 81930 Malaysia",
        location_link: "https://www.google.com/maps/dir//Desaru+Coast,+Johor+Darul+Ta'zim,+Jln+Pantai+3,+81930+Bandar+Penawar,+Johor+Darul+Ta'zim/@1.5403248,104.181203,12z/data=!4m8!4m7!1m0!1m5!1m1!1s0x31da4b5d4f3f562d:0x5f7b288753075fef!2m2!1d104.263605!2d1.5403264?entry=ttu&g_ep=EgoyMDI1MDUyOC4wIKXMDSoASAFQAw%3D%3D",
        price: 159,
        favourite: false,
        rating: 4.5,
        official_website: "https://hotel.hardrock.com/desaru-coast/",
        description: "Your ultimate destination getaway at the leading entertainment hotel in Desaru Coast, Johor, Malaysia. Experience the perfect blend of modern comfort, music-inspired vibes in our stylish hotel rooms and suites.",
        detail: "Rock-themed lobby with live bands, Roxity Kids Club, and walking distance to Adventure Waterpark. Roxity Deluxe with breakfast from ~RM580; 'Stay & Play' includes water park access. Best to avoid Singapore school holidays (May/September); live music every Wednesday evening. Free Fender guitar or turntable rental; 5:00 PM daily guided tour of memorabilia and signature wall."
    },

    'doubletree by hiton hotel': {
        category: "accomodation",
        link_name: "doubletree by hiton hotel",
        name: "DoubleTree By Hilton Hotel",
        image: "/doubletree-by-hilton.jpg",
        room_info: "Blackout curtains, High Speed Internet (WiFi), Airport transportation, Pool, Spa & Fitness",
        payment_info: "RM140/person",
        short_location: "Johor",
        location: "12, Jalan Ngee Heng, Bandar Johor Bahru, 80888 Johor Bahru,",
        location_link: "https://www.google.com/maps?gs_lcrp=EgZjaHJvbWUqCggAEAAY4wIYgAQyCggAEAAY4wIYgAQyFggBEC4YrwEYxwEYgAQYmAUYmQUYngUyBwgCEAAYgAQyBwgDEAAYgAQyBwgEEAAYgAQyBwgFEAAYgAQyBwgGEAAYgAQyBggHEEUYPKgCALACAA&um=1&ie=UTF-8&fb=1&gl=my&sa=X&geocode=KaNQR1LEEtoxMTuwPl3bKBbM&daddr=Ibrahim+International+Business+District,+12,+Jalan+Ngee+Heng,+Bandar+Johor+Bahru,+80888+Johor+Bahru,+Johor+Darul+Ta%27zim",
        price: 140,
        favourite: false,
        rating: 4.6,
        official_website: "https://www.hilton.com/en/hotels/jhbdtdi-doubletree-johor-bahru/?SEO_id=GMB-APAC-DI-JHBDTDI",
        description: "Step into DoubleTree by Hilton Johor Bahru, where contemporary elegance meets vibrant city living. Relax in our stylish rooms, each designed for your utmost comfort. At our Executive Lounge, find exclusive amenities and personalized services. Guests of all ages can enjoy our facilities including a fitness center, steam room, jacuzzi, and an inviting outdoor pool.",
        detail: "City view infinity pool in Johor Bahru, Executive Lounge, EV charging, and walking distance to City Square & immigration. Hilton Honors member rate from ~RM380; free guest parking (Valet RM49/day). Best weekend promos often available for Malaysian residents; ideal for early immigration clearance on Mondays. Warm cookie upon check-in; rooftop pool best for sunset; 20 min by car to Johor Premium Outlets."
    },

    'batu ferringhi hotel': {
        category: "accommodation",
        link_name: "batu ferringhi hotel",
        name: "Shangri-La's Rasa Sayang Resort & Spa, Penang",
        image: "/batu-ferringhi-hotel.jpg",
        room_info: "Garden Wing & adult-only Rasa Wing rooms, 3 outdoor pools, full-service spa, free shuttle to George Town, 5 signature restaurants & bars",
        payment_info: "RM730–RM1,190/night (breakfast included)",
        short_location: "Penang",
        location: "Jalan Batu Ferringhi, Batu Ferringhi, 11100 Penang, Malaysia",
        location_link: "https://www.google.com/maps/place/Shangri-La's+Rasa+Sayang+Resort+%26+Spa",
        price: 730,
        favourite: false,
        rating: 4.5,
        official_website: "https://www.shangri-la.com/penang/rasasayangresort/",
        description: "Set in 30 acres of lush tropical gardens overlooking Batu Ferringhi Beach, Shangri-La's Rasa Sayang Resort & Spa offers two wings (Garden Wing and adult-only Rasa Wing), a full-service spa, three outdoor pools, and five signature restaurants and bars.",
        detail: "Beachfront resort set on 30 acres of tropical gardens with three outdoor pools (two in the Garden Wing + adult-only Rasa Wing), full-service spa, free shuttle to George Town, and five signature restaurants & bars. Standard rooms range USD 174–284/night (≈RM 730–RM 1,190) with breakfast included; check-in 3:00 PM, check-out 12:00 PM. Best visited Mar–Oct for dry, sunny weather and calm seas; weekday stays avoid local weekend crowds. Sea-view rooms recommended; resort undergoing final-phase renovation until Aug 2025 but guest rooms are placed away from worksites; pre-book spa packages & enjoy free water-park access."
    },

    'kuantan resort': {
        category: "accommodation",
        link_name: "kuantan resort",
        name: "Swiss-Garden Beach Resort Kuantan",
        image: "/swiss-garden-beach-resort-kuantan.jpg",
        room_info: "Deluxe & Sea-View rooms, Kids Club & splash pool, spa & sauna, fitness center, tennis courts, 6 F&B outlets, complimentary beach cabanas & water sports",
        payment_info: "RM430/night (breakfast included)",
        short_location: "Pahang",
        location: "2656-2657 Jalan Kuantan-Kemaman, Balok Beach, 26100 Kuantan, Pahang, Malaysia",
        location_link: "https://www.google.com/maps/place/Swiss-Garden+Beach+Resort+Kuantan",
        price: 430,
        favourite: false,
        rating: 4.0,
        official_website: "https://www.swissgarden.com/beach-resort-kuantan/",
        description: "Located beachfront on Balok Beach, Swiss-Garden Beach Resort Kuantan offers 304 renovated rooms (Deluxe & Sea-View), two outdoor pools including a kids' splash pool, full-service spa, sauna, fitness center, tennis courts, and six dining outlets. Guests enjoy complimentary beach cabanas and water sports.",
        detail: "Beachfront Balok Beach resort offering 304 renovated rooms (Deluxe & Sea-View), a free-form outdoor pool with kids' water slide, spa & sauna, fitness center, tennis courts, plus six F&B outlets and complimentary beach cabanas & water sports. Room rates start from USD 96.49/night (≈RM 430) with breakfast; check-in 3:00 PM, check-out 12:00 PM. Best visited Mar–Oct for dry, sunny weather and calm seas; weekday stays avoid local weekend crowds. Sea-view rooms recommended; resort undergoing final-phase renovation until Aug 2025 but guest rooms are placed away from worksites; pre-book spa packages & enjoy free water-park access."
    },
}

module.exports = accomodations;