const accomodations = {
    'pavilion hotel kuala lumpur': {
        category: "accomodation",
        link_name: "pavilion hotel kuala lumpur",
        name: "Pavilion Hotel Kuala Lumpur",
        image: "/pavilion-hotel.jpg",
        room_info: "Stylish Rooms, 24-Hours Concierge, Multiple Dining Options, Spa & Fitness",
        payment_info: "RM200/person",
        short_location: "Kuala Lumpur",
        location: "14 Jalan Pinang, Kuala Lumpur 50450 Malaysia",
        location_link: "https://www.google.com/maps/dir/3.1166212,101.6364583/170,+Jalan+Bukit+Bintang,+55100+Kuala+Lumpur,+Wilayah+Persekutuan+Kuala+Lumpur/@3.1287088,101.6362397,13z/data=!3m1!4b1!4m9!4m8!1m1!4e1!1m5!1m1!1s0x31cc362b89754727:0x5e25d8fab7273d14!2m2!1d101.7148486!2d3.1486329?entry=ttu&g_ep=EgoyMDI1MDUyOC4wIKXMDSoASAFQAw%3D%3D",
        price: 89,
        favourite: false,
        rating: 4.7,
        official_website: "https://www.banyantree.com/malaysia/pavilion-hotel",
        description: "Offering city view and free WiFi, Pavilion Hotel Kuala Lumpur provides luxurious accomodations conveniently located in the city. With elegant dining options, a world-class spa, and modern meeting facilities, it is the perfect destination for both business and leisure travelers."
    },

    'shangri-la kuala lumpur': {
        category: "accomodation",
        link_name: "shangri-la kuala lumpur",
        name: "Shangri-La Kuala Lumpur",
        image: "/shangri-la-kl.jpg",
        room_info: "Blackout curtains, High Speed Internet (WiFi), Airport transportation, Pool, Spa & Fitness",
        payment_info: "RM289/person",
        short_location: "Kuala Lumpur",
        location: "11 Jalan Sultan Ismail, Kuala Lumpur 50250 Malaysia",
        location_link: "https://www.google.com/maps/dir//11,+Jln+Sultan+Ismail,+Kuala+Lumpur,+50250+Kuala+Lumpur,+Wilayah+Persekutuan+Kuala+Lumpur/@3.154074,101.6239383,12z/data=!4m8!4m7!1m0!1m5!1m1!1s0x31cc482a7b0c105f:0xe4d2b948624de950!2m2!1d101.7063403!2d3.1540773?entry=ttu&g_ep=EgoyMDI1MDUyOC4wIKXMDSoASAFQAw%3D%3D",
        price: 289,
        favourite: false,
        rating: 4.8,
        official_website: "https://www.shangri-la.com/kualalumpur/shangrila/",
        description: "A traditional greeting from the heart awaits each of our guests on arrival to the Shangri-La Hotel, Kuala Lumpur. Our hotel is a welcome retreat from the bustling streets of the city; relax poolside in our tropical gardens, re-connect over drinks in our sun drenched lounge or rejuvenate and recharge at our Health Club & SPA."
    },

    'sunway resort hotel': {
        category: "accomodation",
        link_name: "sunway resort hotel",
        name: "Sunway Resort Hotel",
        image: "/sunway-resort-hotel-spa.jpg",
        room_info: "Blackout curtains, High Speed Internet (WiFi), Airport transportation, Pool, Spa & Fitness",
        payment_info: "RM300/person",
        short_location: "Selangor",
        location: "1, Persiaran Lagoon, Bandar Sunway, 47500 Petaling Jaya, Selangor",
        location_link: "https://www.google.com/maps/dir//1,+Persiaran+Lagoon,+Bandar+Sunway,+47500+Petaling+Jaya,+Selangor/@3.1195136,101.6266752,12z/data=!4m8!4m7!1m0!1m5!1m1!1s0x31cc4c812c0a18cb:0x96bc62906ec10444!2m2!1d101.6087575!2d3.071118?entry=ttu&g_ep=EgoyMDI1MDUyOC4wIKXMDSoASAFQAw%3D%3D",
        price: 300,
        favourite: false,
        rating: 4.9,
        official_website: "https://www.sunwayhotels.com/sunway-resort",
        description: "Sunway Resort Hotel, formerly Sunway Resort Hotel & Spa, is Kuala Lumpur’s most iconic 5-star hotel, located in Sunway City Kuala Lumpur—Malaysia’s premier entertainment and hospitality destination. The hotel features 477 smart, environmentally friendly rooms and suites, designed and equipped with state-of-the-art technology. Specialty suites cater to business travellers, families, wellness seekers and luxury enthusiasts. Guests can enjoy exclusive lounges, family-friendly zones like Waterventure and extraordinary dining—from the world-class Gordon Ramsay Bar & Grill, the chef’s first restaurant in Malaysia and outside London, to laid-back poolside dining at Sunset Terrace."
    },

    'one world hotel': {
        category: "accomodation",
        link_name: "one world hotel",
        name: "One World Hotel",
        image: "/one-world-hotel.jpg",
        room_info: "Blackout curtains, High Speed Internet (WiFi), Airport transportation, Pool, Spa & Fitness",
        payment_info: "RM300/person",
        short_location: "Selangor",
        location: "First Avenue Bandar Utama City Centre, Petaling Jaya 47800 Malaysia",
        location_link: "https://www.google.com/maps/dir//City+Centre,+First+Avenue,+Lebuh+Bandar+Utama,+Bandar+Utama,+47800+Petaling+Jaya,+Selangor/@3.1473955,101.5347482,12z/data=!4m8!4m7!1m0!1m5!1m1!1s0x31cc492b58970a77:0x2d3fe930d5bb6ad7!2m2!1d101.6171502!2d3.1473987?entry=ttu&g_ep=EgoyMDI1MDUyOC4wIKXMDSoASAFQAw%3D%3D",
        price: 300,
        favourite: false,
        rating: 4.6,
        official_website: "https://www.tripadvisor.com.my/Commerce?p=TABAIndependentHotels&src=0&geo=656672&from=Hotel_Review&area=&slot=2&matchID=1&oos=0&cnt=1&silo=30356&bucket=875171&nrank=1&crank=1&clt=CLD&tm=328875077&managed=false&capped=false&gosox=5_3Y6UYwwGjgw_c7hEwIkaMWncZYqB1tN1tJAU3Ybs1UzJsHmO1A0W8n_IVX36vvypxiViMSB6kUDmyTXVRwVQ&bapid=2&cs=1f4b94b941584f8bca73aeb6ca214b52f&ba_uid=df55e2d0-d067-4579-b3a6-156f28c4adad",
        description: "The award-winning 5-star One World Hotel, Petaling Jaya features 6 categories of 452 contemporary guestrooms and suites furnished with luxurious amenities, facilities and services. Conveniently adjoined to the world’s 7th largest mall, 1 Utama comprises of more than 650 retail outlets, with direct access to the Bandar Utama MRT Station and just minutes away from downtown Kuala Lumpur and the Kuala Lumpur International Airport. "
    },

    'swiss garden resort kuantan': {
        category: "accomodation",
        link_name: "swiss garden resort kuantan",
        name: "Swiss Garden Resort Kuantan",
        image: "/swiss-garden-resort.jpg",
        room_info: "Blackout curtains, High Speed Internet (WiFi), Airport transportation, Pool, Spa & Fitness",
        payment_info: "RM280/person",
        short_location: "Pahang",
        location: "2656-2657 Jln Kuantan - Kemaman, Kuantan 26100 Malaysia",
        location_link: "https://www.google.com/maps?gs_lcrp=EgZjaHJvbWUqCggAEAAY4wIYgAQyCggAEAAY4wIYgAQyFggBEC4YrwEYxwEYgAQYmAUYmgUYngUyBwgCEAAYgAQyBwgDEAAYgAQyDAgEEAAYFBiHAhiABDIICAUQABgWGB4yCAgGEAAYFhgeMgYIBxBFGDzSAQgxMTc4ajBqN6gCALACAA&um=1&ie=UTF-8&fb=1&gl=my&sa=X&geocode=KTf1Jg11sMgxMTInBrGEU9A1&daddr=2656~2657,+Mukim+Balok+Beach+Beserah+26100,+Kuantan,+Pahang",
        price: 280,
        favourite: false,
        rating: 4.7,
        official_website: "https://www.swissgarden.com/beach-resort-kuantan/",
        description: "Sky, sea and sun provide a peaceful backdrop to a landscape so alluring it stirs the emotions. The vivid colours of nature's palette glow in the soft tropical light accenting the purity of air, water and land. From the colors of the sunset, to soothing air greeting you with a warm embrace; the family and kids friendly Swiss- Garden Beach Resort, Kuantan, offers sensual delights at every turn with a beautiful beach front, fun and enjoyable kids club as well as a fun-filled splash pool perfect for family staycation."
    },

    'hyatt regency resort kuantan': {
        category: "accomodation",
        link_name: "hyatt regency resort kuantan",
        name: "Hyatt Regency Resort Kuantan",
        image: "/hyatt-regency-kuantan.jpg",
        room_info: "Blackout curtains, High Speed Internet (WiFi), Airport transportation, Pool, Spa & Fitness",
        payment_info: "RM190/person",
        short_location: "Pahang",
        location: "Teluk Cempedak, Kuantan 25050 Malaysia",
        location_link: "https://www.google.com/maps/dir/3.9154832,103.4159196/Teluk+Cempedak,+25050+Kuantan,+25050+Pahang/@3.8730095,103.2830537,12z/data=!4m8!4m7!1m0!1m5!1m1!1s0x31c8a54547faa933:0x339d68da41de1544!2m2!1d103.3712922!2d3.8113542?entry=ttu&g_ep=EgoyMDI1MDUyOC4wIKXMDSoASAFQAw%3D%3D",
        price: 190,
        favourite: false,
        rating: 4.9,
        official_website: "https://www.hyatt.com/hyatt-regency/en-US/kuakt-hyatt-regency-kuantan-resort?src=corp_lclb_google_seo_kuakt&utm_source=google&utm_medium=organic&utm_campaign=lmr",
        description: "Located on the stunning beachfront of Teluk Cempedak, on the east coast of peninsular Malaysia and within proximity to Kuantan city, capital of Pahang, the refurbished Hyatt Regency Kuantan Resort is the perfect place for making meaningful connections that last a lifetime. 301 guestrooms and suites that have been completely rebuilt, including new family oriented rooms"
    },

    'hard rock hotel desaru': {
        category: "accomodation",
        link_name: "hard rock hotel desaru",
        name: "Hard Rock Hotel Desaru",
        image: "/hard-rock-hotel-desaru.jpg",
        room_info: "Blackout curtains, High Speed Internet (WiFi), Airport transportation, Pool, Spa & Fitness",
        payment_info: "RM159/person",
        short_location: "Johor",
        location: "Jalan Pantai 3, Bandar Penawar 81930 Malaysia",
        location_link: "https://www.google.com/maps/dir//Desaru+Coast,+Johor+Darul+Ta'zim,+Jln+Pantai+3,+81930+Bandar+Penawar,+Johor+Darul+Ta'zim/@1.5403248,104.181203,12z/data=!4m8!4m7!1m0!1m5!1m1!1s0x31da4b5d4f3f562d:0x5f7b288753075fef!2m2!1d104.263605!2d1.5403264?entry=ttu&g_ep=EgoyMDI1MDUyOC4wIKXMDSoASAFQAw%3D%3D",
        price: 159,
        favourite: false,
        rating: 4.5,
        official_website: "https://hotel.hardrock.com/desaru-coast/",
        description: "Your ultimate destination getaway at the leading entertainment hotel in Desaru Coast, Johor, Malaysia. Experience the perfect blend of modern comfort, music-inspired vibes in our stylish hotel rooms and suites."
    },

    'doubletree by hiton hotel': {
        category: "accomodation",
        link_name: "doubletree by hiton hotel",
        name: "DoubleTree By Hilton Hotel",
        image: "/doubletree-by-hilton.jpg",
        room_info: "Blackout curtains, High Speed Internet (WiFi), Airport transportation, Pool, Spa & Fitness",
        payment_info: "RM140/person",
        short_location: "Johor",
        location: "12, Jalan Ngee Heng, Bandar Johor Bahru, 80888 Johor Bahru",
        location_link: "https://www.google.com/maps?gs_lcrp=EgZjaHJvbWUqCggAEAAY4wIYgAQyCggAEAAY4wIYgAQyFggBEC4YrwEYxwEYgAQYmAUYmQUYngUyBwgCEAAYgAQyBwgDEAAYgAQyBwgEEAAYgAQyBwgFEAAYgAQyBwgGEAAYgAQyBggHEEUYPKgCALACAA&um=1&ie=UTF-8&fb=1&gl=my&sa=X&geocode=KaNQR1LEEtoxMTuwPl3bKBbM&daddr=Ibrahim+International+Business+District,+12,+Jalan+Ngee+Heng,+Bandar+Johor+Bahru,+80888+Johor+Bahru,+Johor+Darul+Ta%27zim",
        price: 140,
        favourite: false,
        rating: 4.6,
        official_website: "https://www.hilton.com/en/hotels/jhbdtdi-doubletree-johor-bahru/?SEO_id=GMB-APAC-DI-JHBDTDI",
        description: "Step into DoubleTree by Hilton Johor Bahru, where contemporary elegance meets vibrant city living. Relax in our stylish rooms, each designed for your utmost comfort. At our Executive Lounge, find exclusive amenities and personalized services. Guests of all ages can enjoy our facilities including a fitness center, steam room, jacuzzi, and an inviting outdoor pool."
    },

    'berjaya langkawi resort': {
        category: "accomodation",
        link_name: "berjaya langkawi resort",
        name: "Berjaya Langkawi Resort",
        image: "/berjaya-langkawi-resort.jpg",
        room_info: "Blackout curtains, High Speed Internet (WiFi), Airport transportation, Pool, Spa & Fitness",
        payment_info: "RM239/person",
        short_location: "Kedah",
        location: "Karung Berkunci 200 Burau Bay, 07000 Langkawi, Kedah",
        location_link: "https://www.google.com/maps/place/Berjaya+Langkawi+Resort/data=!4m2!3m1!1s0x0:0x3ebb3da17d711ce7?sa=X&ved=1t:2428&ictx=111",
        price: 239,
        favourite: false,
        rating: 4.8,
        official_website: "https://www.berjayahotel.com/langkawi",
        description: "Berjaya Langkawi Resort is celebrated by many travelers for its tranquil atmosphere and picturesque location, nestled in a rainforest with stunning beach views."
    },

    'perdana kota bharu': {
        category: "accomodation",
        link_name: "perdana kota bharu",
        name: "Perdana Kota Bharu",
        image: "/perdana-kota-bharu.jpg",
        room_info: "Blackout curtains, High Speed Internet (WiFi), Airport transportation, Pool, Spa & Fitness",
        payment_info: "RM200/person",
        short_location: "Kelantan",
        location: "Jalan Mahmood, Kota Bharu 15200 Malaysia",
        location_link: "https://www.google.com/maps?sca_esv=aa7ea73e80d9b827&sxsrf=AE3TifPAXZ4SyC5UN3H3-qLYzTNvun7uzA:1750563073065&uact=5&gs_lp=Egxnd3Mtd2l6LXNlcnAiElBlcmRhbmEgS290YSBCaGFydTIREC4YgAQYxwEYmAUYmQUYrwEyBhAAGBYYHjIGEAAYFhgeMgYQABgWGB4yBhAAGBYYHjIGEAAYFhgeMgYQABgWGB4yBhAAGBYYHjIGEAAYFhgeMgYQABgWGB4yIBAuGIAEGMcBGJgFGJkFGK8BGJcFGNwEGN4EGOAE2AEBSJwVUKUEWMkScAJ4AZABA5gBoAGgAZsPqgEEMTguNLgBA8gBAPgBAfgBApgCBKACpAKoAhLCAgoQABiwAxjWBBhHwgINEAAYgAQYsAMYQxiKBcICGRAuGIAEGLADGEMYxwEYmAUYigUYmgUYrwHCAh8QLhiABBiwAxhDGMcBGJgFGMgDGIoFGJoFGK8B2AEBwgIiEC4YgAQYsAMYQxjHARiYBRjIAxiZBRiKBRieBRivAdgBAcICHxAuGIAEGLADGEMYxwEYmAUYyAMYmQUYigUYrwHYAQHCAgoQIxiABBgnGIoFwgIcEC4YgAQYsQMYQxjHARiYBRiKBRiaBRieBRivAcICBRAAGIAEwgIrEC4YgAQYsQMYQxjHARiYBRiKBRiaBRieBRivARiXBRjcBBjeBBjgBNgBAcICBxAjGCcY6gLCAg0QIxjwBRgnGMkCGOoCwgIKECMY8AUYJxjqAsICDRAuGNEDGMcBGCcY6gLCAgcQLhgnGOoCwgIiEC4YgAQYQxi0AhjHARiYBRjIAxiKBRiaBRjqAhivAdgBAcICJRAuGIAEGEMYtAIYxwEYmAUYyAMYmQUYigUY6gIYngUYrwHYAQHCAiIQLhiABBhDGLQCGMcBGJgFGMgDGJkFGIoFGOoCGK8B2AEBmAME8QWoNVmD9rS49IgGAZAGFLoGBggBEAEYCJIHAzIuMqAH2dICsgcDMC4yuAeYAsIHAzItNMgHEQ&um=1&ie=UTF-8&fb=1&gl=my&sa=X&geocode=KRm0N8DEr7YxMaeaQEULtwx9&daddr=Jln+Mahmood,+Bandar+Kota+Bharu,+15000+Kota+Bharu,+Kelantan",
        price: 200,
        favourite: false,
        rating: 4.9,
        official_website: "https://perdana.attanahotels.com/perdana-kota-bharu",
        description: "Perdana Kota Bharu is the first premier hotel located in capital city of Kelantan, circled by tourist attractions, historical heritage places and local eateries"
    },

    'rc hotel': {
        category: "accomodation",
        link_name: "rc hotel",
        name: "RC Hotel",
        image: "/rc-hotel.jpg",
        room_info: "Blackout curtains, High Speed Internet (WiFi), Airport transportation, Pool, Spa & Fitness",
        payment_info: "RM142/person",
        short_location: "Melaka",
        location: "No. 36, Jalan Kampung Pantai, Melaka 75200 Malaysia",
        location_link: "https://www.google.com/maps?gs_lcrp=EgZjaHJvbWUqCggAEAAY4wIYgAQyCggAEAAY4wIYgAQyEwgBEC4YrwEYxwEYgAQYmAUYmQUyBwgCEAAYgAQyBwgDEAAYgAQyBwgEEAAYgAQyCAgFEAAYFhgeMggIBhAAGBYYHjIGCAcQRRg8qAIAsAIA&um=1&ie=UTF-8&fb=1&gl=my&sa=X&geocode=Kbu7dq7e8dExMS-MxI0_ju1x&daddr=No+36,+Jalan+Kampung+Pantai,+75100+Melaka",
        price: 142,
        favourite: false,
        rating: 4.9,
        official_website: "http://www.rchotelmelaka.com/",
        description: "See why so many travellers make RC Hotel their hotel of choice when visiting Melaka. Providing an ideal mix of value, comfort and convenience, it offers a charming setting with an array of amenities designed for travellers like you."
    },

    'parkroyal penang resort': {
        category: "accomodation",
        link_name: "parkroyal penang resort",
        name: "ParkRoyal Penang Resort",
        image: "/parkroyal-penang-resort.jpg",
        room_info: "Blackout curtains, High Speed Internet (WiFi), Airport transportation, Pool, Spa & Fitness",
        payment_info: "RM249/person",
        short_location: "Penang",
        location: "Batu Ferringhi Beach, Batu Ferringhi, Penang Island 11100 Malaysia",
        location_link: "https://www.google.com/maps?gs_lcrp=EgZjaHJvbWUqCggAEAAY4wIYgAQyCggAEAAY4wIYgAQyFggBEC4YrwEYxwEYgAQYmAUYmgUYngUyBwgCEAAYgAQyBwgDEAAYgAQyBwgEEAAYgAQyBwgFEAAYgAQyBggGEEUYPDIGCAcQRRg8qAIAsAIA&um=1&ie=UTF-8&fb=1&gl=my&sa=X&geocode=KbUiyChS3UowMcWr4zSiKDfl&daddr=PARKROYAL+Penang+Resort+Batu+Ferringhi+Beach,+11100+Batu+Ferringhi,+Pulau+Pinang",
        price: 249,
        favourite: false,
        rating: 4.9,
        official_website: "https://www.tripadvisor.com.my/Commerce?p=TABAIndependentHotels&src=0&geo=306935&from=Hotel_Review&area=&slot=1&matchID=1&oos=0&cnt=1&silo=30356&bucket=875171&nrank=1&crank=1&clt=CLD&tm=330475628&managed=false&capped=false&gosox=5_3Y6UYwwGjgw_c7hEwIkYVgngML5Wh2w8zYZk95mQ6GhsuiS3zTbU-Zd3b2fSEi040f9VlmykMdEp0QmeFyBQ&bapid=1&cs=1adab4cf86fd26f41bf80446f6cdc9715&ba_uid=7f0eec1b-ea99-411f-ad36-e950939bdc8f",
        description: "PARKROYAL Penang Resort is a five-star beach resort located along the beautiful shorelines of Penang. The resort nestled in a lush tropical greenery setting offers unparalleled experiences from exquisite gourmet dining, state-of-the-art facilities and a host of family-friendly activities where curated experiences are brought to life."
    },

    'tui blue the haven': {
        category: "accomodation",
        link_name: "tui blue the haven",
        name: "Tui Blue The Haven",
        image: "/tui-blue-the-haven.jpg",
        room_info: "Blackout curtains, High Speed Internet (WiFi), Airport transportation, Pool, Spa & Fitness",
        payment_info: "RM349/person",
        short_location: "Perak",
        location: "Persiaran Lembah Perpaduan, Ipoh 31150 Malaysia",
        location_link: "https://www.google.com/maps?gs_lcrp=EgZjaHJvbWUqCggAEAAY4wIYgAQyCggAEAAY4wIYgAQyFggBEC4YrwEYxwEYgAQYmAUYmgUYngUyBwgCEAAYgAQyBwgDEAAYgAQyBwgEEAAYgAQyBwgFEAAYgAQyCggGEAAYgAQYogQyBggHEEUYPKgCALACAA&um=1&ie=UTF-8&fb=1&gl=my&sa=X&geocode=KdMGFHlV7coxMa366Dy6Wyei&daddr=Persiaran+Lembah+Perpaduan,+31150+Ipoh,+Perak",
        price: 349,
        favourite: false,
        rating: 5.0,
        official_website: "https://tuibluethehavenipoh.com/",
        description: "TUI BLUE The Haven Ipoh is set in nature – on the edge of a virgin forest, amidst the flora and fauna of a prehistoric site dating over 280 million years – located merely 15 minutes from the city centre. It is possibly the only one of its kind in the world where you can live by a primary forest, in close proximity to the city."
    },

    'le meridien kota kinabalu': {
        category: "accomodation",
        link_name: "le meridien kota kinabalu",
        name: "Le Meridien Kota Kinabalu",
        image: "/le-meridien-kota-kinabalu.jpg",
        room_info: "Blackout curtains, High Speed Internet (WiFi), Airport transportation, Pool, Spa & Fitness",
        payment_info: "RM199/person",
        short_location: "Sabah",
        location: "Jalan Tun Fuad Stephens Sinsuran, Kota Kinabalu 88000 Malaysia",
        location_link: "https://www.google.com/maps?gs_lcrp=EgZjaHJvbWUqBwgAEAAYgAQyBwgAEAAYgAQyBwgBEAAYgAQyBwgCEAAYgAQyBwgDEAAYgAQyBwgEEAAYgAQyBwgFEAAYgAQyBwgGEAAYgAQyBggHEEUYPNIBBzM4M2owajeoAgCwAgA&um=1&ie=UTF-8&fb=1&gl=my&sa=X&geocode=KX9wYI2RaTsyMaRPULdapPE5&daddr=Jln+Tun+Fuad+Stephens,+Sinsuran,+88000+Kota+Kinabalu",
        price: 199,
        favourite: false,
        rating: 5.0,
        official_website: "https://www.tripadvisor.com.my/Commerce?p=TABAIndependentHotels&src=0&geo=582314&from=Hotel_Review&area=&slot=1&matchID=1&oos=0&cnt=1&silo=30356&bucket=875171&nrank=1&crank=1&clt=CLD&tm=330476246&managed=false&capped=false&gosox=5_3Y6UYwwGjgw_c7hEwIkaMWncZYqB1tN1tJAU3Ybs1Bd-yEgZ171WY5ATY3dzvFrbBAaiad-NpAHkDeCFxa0w&bapid=1&cs=14443443c8891259e55fbe646c9a9c35a&ba_uid=31794242-1b27-47c6-a39b-5b9069c83e08",
        description: "Le Meridien Kota Kinabalu is a contemporary 5 star hotel, strategically located at the heart and city center of downtown Kota Kinabalu across the fresh and handicraft markets and Kota Kinabalu waterfront."
    },

    'permai rainforest resort': {
        category: "accomodation",
        link_name: "permai rainforest resort",
        name: "Permai Rainforest Resort",
        image: "/permai-rainforest-resort.jpg",
        room_info: "Blackout curtains, High Speed Internet (WiFi), Airport transportation, Pool, Spa & Fitness",
        payment_info: "RM259/person",
        short_location: "Sarawak",
        location: "Teluk Penyuk Santubong, Kuching 93050 Malaysia",
        location_link: "https://www.google.com/maps?gs_lcrp=EgZjaHJvbWUqEAgAEAAYkQIY4wIYgAQYigUyEAgAEAAYkQIY4wIYgAQYigUyGQgBEC4YrwEYxwEYkQIYgAQYigUYmAUYmgUyBwgCEAAYgAQyBwgDEAAYgAQyBwgEEAAYgAQyBwgFEAAYgAQyBwgGEAAYgAQyBggHEEUYPKgCALACAA&um=1&ie=UTF-8&fb=1&gl=my&sa=X&geocode=KRv3xUl3p_sxMQmBSLsvmAUq&daddr=Teluk+Penyuk+Santubong,+Jalan+Sultan+Tengah,+93050+Kuching,+Sarawak",
        price: 259,
        favourite: false,
        rating: 5.0,
        official_website: "http://www.permairainforest.com/",
        description: "Permai Rainforest Resort is an eco-resort set in pristine Borneo rainforest located by the beach at the foot of mystical Mount Santubong, Sarawak. Carefully designed to minimize impact on the natural environment, it offers a unique rainforest experience and a variety of activities from dolphin watching to high ropes courses and guided kayaking tours."
    },
}

module.exports = accomodations;