const accomodations = {
    'pavilion hotel kuala lumpur': {
        category: "accomodation",
        link_name: "pavilion hotel kuala lumpur",
        name: "Pavilion Hotel Kuala Lumpur",
        image: "/pavilion-hotel.jpg",
        room_info: "Stylish Rooms, 24-Hours Concierge, Multiple Dining Options, Spa & Fitness",
        payment_info: "RM200/person",
        short_location: "Kuala Lumpur",
        location: "14 Jalan Pinang, Kuala Lumpur 50450 Malaysia",
        location_link: "https://www.google.com/maps/dir/3.1166212,101.6364583/170,+Jalan+Bukit+Bintang,+55100+Kuala+Lumpur,+Wilayah+Persekutuan+Kuala+Lumpur/@3.1287088,101.6362397,13z/data=!3m1!4b1!4m9!4m8!1m1!4e1!1m5!1m1!1s0x31cc362b89754727:0x5e25d8fab7273d14!2m2!1d101.7148486!2d3.1486329?entry=ttu&g_ep=EgoyMDI1MDUyOC4wIKXMDSoASAFQAw%3D%3D",
        price: 89,
        favourite: false,
        rating: 4.7,
        official_website: "https://www.banyantree.com/malaysia/pavilion-hotel",
        description: "Offering city view and free WiFi, Pavilion Hotel Kuala Lumpur provides luxurious accomodations conveniently located in the city. With elegant dining options, a world-class spa, and modern meeting facilities, it is the perfect destination for both business and leisure travelers."
    },

    'shangri-la kuala lumpur': {
        category: "accomodation",
        link_name: "shangri-la kuala lumpur",
        name: "Shangri-La Kuala Lumpur",
        image: "/shangri-la-kl.jpg",
        room_info: "Blackout curtains, High Speed Internet (WiFi), Airport transportation, Pool, Spa & Fitness",
        payment_info: "RM289/person",
        short_location: "Kuala Lumpur",
        location: "11 Jalan Sultan Ismail, Kuala Lumpur 50250 Malaysia",
        location_link: "https://www.google.com/maps/dir//11,+Jln+Sultan+Ismail,+Kuala+Lumpur,+50250+Kuala+Lumpur,+Wilayah+Persekutuan+Kuala+Lumpur/@3.154074,101.6239383,12z/data=!4m8!4m7!1m0!1m5!1m1!1s0x31cc482a7b0c105f:0xe4d2b948624de950!2m2!1d101.7063403!2d3.1540773?entry=ttu&g_ep=EgoyMDI1MDUyOC4wIKXMDSoASAFQAw%3D%3D",
        price: 289,
        favourite: false,
        rating: 4.8,
        official_website: "https://www.shangri-la.com/kualalumpur/shangrila/",
        description: "A traditional greeting from the heart awaits each of our guests on arrival to the Shangri-La Hotel, Kuala Lumpur. Our hotel is a welcome retreat from the bustling streets of the city; relax poolside in our tropical gardens, re-connect over drinks in our sun drenched lounge or rejuvenate and recharge at our Health Club & SPA."
    },

    'sunway resort hotel': {
        category: "accomodation",
        link_name: "sunway resort hotel",
        name: "Sunway Resort Hotel",
        image: "/sunway-resort-hotel-spa.jpg",
        room_info: "Blackout curtains, High Speed Internet (WiFi), Airport transportation, Pool, Spa & Fitness",
        payment_info: "RM300/person",
        short_location: "Selangor",
        location: "1, Persiaran Lagoon, Bandar Sunway, 47500 Petaling Jaya, Selangor",
        location_link: "https://www.google.com/maps/dir//1,+Persiaran+Lagoon,+Bandar+Sunway,+47500+Petaling+Jaya,+Selangor/@3.1195136,101.6266752,12z/data=!4m8!4m7!1m0!1m5!1m1!1s0x31cc4c812c0a18cb:0x96bc62906ec10444!2m2!1d101.6087575!2d3.071118?entry=ttu&g_ep=EgoyMDI1MDUyOC4wIKXMDSoASAFQAw%3D%3D",
        price: 300,
        favourite: false,
        rating: 4.9,
        official_website: "https://www.sunwayhotels.com/sunway-resort",
        description: "Sunway Resort Hotel, formerly Sunway Resort Hotel & Spa, is Kuala Lumpur’s most iconic 5-star hotel, located in Sunway City Kuala Lumpur—Malaysia’s premier entertainment and hospitality destination. The hotel features 477 smart, environmentally friendly rooms and suites, designed and equipped with state-of-the-art technology. Specialty suites cater to business travellers, families, wellness seekers and luxury enthusiasts. Guests can enjoy exclusive lounges, family-friendly zones like Waterventure and extraordinary dining—from the world-class Gordon Ramsay Bar & Grill, the chef’s first restaurant in Malaysia and outside London, to laid-back poolside dining at Sunset Terrace."
    },

    'one world hotel': {
        category: "accomodation",
        link_name: "one world hotel",
        name: "One World Hotel",
        image: "/one-world-hotel.jpg",
        room_info: "Blackout curtains, High Speed Internet (WiFi), Airport transportation, Pool, Spa & Fitness",
        payment_info: "RM300/person",
        short_location: "Selangor",
        location: "First Avenue Bandar Utama City Centre, Petaling Jaya 47800 Malaysia",
        location_link: "https://www.google.com/maps/dir//City+Centre,+First+Avenue,+Lebuh+Bandar+Utama,+Bandar+Utama,+47800+Petaling+Jaya,+Selangor/@3.1473955,101.5347482,12z/data=!4m8!4m7!1m0!1m5!1m1!1s0x31cc492b58970a77:0x2d3fe930d5bb6ad7!2m2!1d101.6171502!2d3.1473987?entry=ttu&g_ep=EgoyMDI1MDUyOC4wIKXMDSoASAFQAw%3D%3D",
        price: 300,
        favourite: false,
        rating: 4.6,
        official_website: "https://www.tripadvisor.com.my/Commerce?p=TABAIndependentHotels&src=0&geo=656672&from=Hotel_Review&area=&slot=2&matchID=1&oos=0&cnt=1&silo=30356&bucket=875171&nrank=1&crank=1&clt=CLD&tm=328875077&managed=false&capped=false&gosox=5_3Y6UYwwGjgw_c7hEwIkaMWncZYqB1tN1tJAU3Ybs1UzJsHmO1A0W8n_IVX36vvypxiViMSB6kUDmyTXVRwVQ&bapid=2&cs=1f4b94b941584f8bca73aeb6ca214b52f&ba_uid=df55e2d0-d067-4579-b3a6-156f28c4adad",
        description: "The award-winning 5-star One World Hotel, Petaling Jaya features 6 categories of 452 contemporary guestrooms and suites furnished with luxurious amenities, facilities and services. Conveniently adjoined to the world’s 7th largest mall, 1 Utama comprises of more than 650 retail outlets, with direct access to the Bandar Utama MRT Station and just minutes away from downtown Kuala Lumpur and the Kuala Lumpur International Airport. "
    },

    'swiss garden resort kuantan': {
        category: "accomodation",
        link_name: "swiss garden resort kuantan",
        name: "Swiss Garden Resort Kuantan",
        image: "/swiss-garden-resort.jpg",
        room_info: "Blackout curtains, High Speed Internet (WiFi), Airport transportation, Pool, Spa & Fitness",
        payment_info: "RM280/person",
        short_location: "Pahang",
        location: "2656-2657 Jln Kuantan - Kemaman, Kuantan 26100 Malaysia",
        location_link: "https://www.google.com/maps?gs_lcrp=EgZjaHJvbWUqCggAEAAY4wIYgAQyCggAEAAY4wIYgAQyFggBEC4YrwEYxwEYgAQYmAUYmgUYngUyBwgCEAAYgAQyBwgDEAAYgAQyDAgEEAAYFBiHAhiABDIICAUQABgWGB4yCAgGEAAYFhgeMgYIBxBFGDzSAQgxMTc4ajBqN6gCALACAA&um=1&ie=UTF-8&fb=1&gl=my&sa=X&geocode=KTf1Jg11sMgxMTInBrGEU9A1&daddr=2656~2657,+Mukim+Balok+Beach+Beserah+26100,+Kuantan,+Pahang",
        price: 280,
        favourite: false,
        rating: 4.7,
        official_website: "https://www.swissgarden.com/beach-resort-kuantan/",
        description: "Sky, sea and sun provide a peaceful backdrop to a landscape so alluring it stirs the emotions. The vivid colours of nature's palette glow in the soft tropical light accenting the purity of air, water and land. From the colors of the sunset, to soothing air greeting you with a warm embrace; the family and kids friendly Swiss- Garden Beach Resort, Kuantan, offers sensual delights at every turn with a beautiful beach front, fun and enjoyable kids club as well as a fun-filled splash pool perfect for family staycation."
    },

    'hyatt regency resort kuantan': {
        category: "accomodation",
        link_name: "hyatt regency resort kuantan",
        name: "Hyatt Regency Resort Kuantan",
        image: "/hyatt-regency-kuantan.jpg",
        room_info: "Blackout curtains, High Speed Internet (WiFi), Airport transportation, Pool, Spa & Fitness",
        payment_info: "RM190/person",
        short_location: "Pahang",
        location: "Teluk Cempedak, Kuantan 25050 Malaysia",
        location_link: "https://www.google.com/maps/dir/3.9154832,103.4159196/Teluk+Cempedak,+25050+Kuantan,+25050+Pahang/@3.8730095,103.2830537,12z/data=!4m8!4m7!1m0!1m5!1m1!1s0x31c8a54547faa933:0x339d68da41de1544!2m2!1d103.3712922!2d3.8113542?entry=ttu&g_ep=EgoyMDI1MDUyOC4wIKXMDSoASAFQAw%3D%3D",
        price: 190,
        favourite: false,
        rating: 4.9,
        official_website: "https://www.hyatt.com/hyatt-regency/en-US/kuakt-hyatt-regency-kuantan-resort?src=corp_lclb_google_seo_kuakt&utm_source=google&utm_medium=organic&utm_campaign=lmr",
        description: "Located on the stunning beachfront of Teluk Cempedak, on the east coast of peninsular Malaysia and within proximity to Kuantan city, capital of Pahang, the refurbished Hyatt Regency Kuantan Resort is the perfect place for making meaningful connections that last a lifetime. 301 guestrooms and suites that have been completely rebuilt, including new family oriented rooms"
    },

    'hard rock hotel desaru': {
        category: "accomodation",
        link_name: "hard rock hotel desaru",
        name: "Hard Rock Hotel Desaru",
        image: "/hard-rock-hotel-desaru.jpg",
        room_info: "Blackout curtains, High Speed Internet (WiFi), Airport transportation, Pool, Spa & Fitness",
        payment_info: "RM159/person",
        short_location: "Johor",
        location: "Jalan Pantai 3, Bandar Penawar 81930 Malaysia",
        location_link: "https://www.google.com/maps/dir//Desaru+Coast,+Johor+Darul+Ta'zim,+Jln+Pantai+3,+81930+Bandar+Penawar,+Johor+Darul+Ta'zim/@1.5403248,104.181203,12z/data=!4m8!4m7!1m0!1m5!1m1!1s0x31da4b5d4f3f562d:0x5f7b288753075fef!2m2!1d104.263605!2d1.5403264?entry=ttu&g_ep=EgoyMDI1MDUyOC4wIKXMDSoASAFQAw%3D%3D",
        price: 159,
        favourite: false,
        rating: 4.5,
        official_website: "https://hotel.hardrock.com/desaru-coast/",
        description: "Your ultimate destination getaway at the leading entertainment hotel in Desaru Coast, Johor, Malaysia. Experience the perfect blend of modern comfort, music-inspired vibes in our stylish hotel rooms and suites."
    },

    'doubletree by hiton hotel': {
        category: "accomodation",
        link_name: "doubletree by hiton hotel",
        name: "DoubleTree By Hilton Hotel",
        image: "/doubletree-by-hilton.jpg",
        room_info: "Blackout curtains, High Speed Internet (WiFi), Airport transportation, Pool, Spa & Fitness",
        payment_info: "RM140/person",
        short_location: "Johor",
        location: "12, Jalan Ngee Heng, Bandar Johor Bahru, 80888 Johor Bahru,",
        location_link: "https://www.google.com/maps?gs_lcrp=EgZjaHJvbWUqCggAEAAY4wIYgAQyCggAEAAY4wIYgAQyFggBEC4YrwEYxwEYgAQYmAUYmQUYngUyBwgCEAAYgAQyBwgDEAAYgAQyBwgEEAAYgAQyBwgFEAAYgAQyBwgGEAAYgAQyBggHEEUYPKgCALACAA&um=1&ie=UTF-8&fb=1&gl=my&sa=X&geocode=KaNQR1LEEtoxMTuwPl3bKBbM&daddr=Ibrahim+International+Business+District,+12,+Jalan+Ngee+Heng,+Bandar+Johor+Bahru,+80888+Johor+Bahru,+Johor+Darul+Ta%27zim",
        price: 140,
        favourite: false,
        rating: 4.6,
        official_website: "https://www.hilton.com/en/hotels/jhbdtdi-doubletree-johor-bahru/?SEO_id=GMB-APAC-DI-JHBDTDI",
        description: "Step into DoubleTree by Hilton Johor Bahru, where contemporary elegance meets vibrant city living. Relax in our stylish rooms, each designed for your utmost comfort. At our Executive Lounge, find exclusive amenities and personalized services. Guests of all ages can enjoy our facilities including a fitness center, steam room, jacuzzi, and an inviting outdoor pool."
    },

    // --- NEW ACCOMMODATIONS ADDED BELOW ---

    'the datai langkawi': {
        category: "accomodation",
        link_name: "the datai langkawi",
        name: "The Datai Langkawi",
        image: "/the-datai-langkawi.jpg",
        room_info: "Luxury rainforest villas, private beach, multiple dining options, spa, golf course, nature activities",
        payment_info: "RM1500/person",
        short_location: "Kedah",
        location: "Jalan Teluk Datai, 07000 Langkawi, Kedah Darul Aman, Malaysia",
        location_link: "https://www.google.com/maps/place/The+Datai+Langkawi/@6.4172582,99.6970723,17z/data=!3m1!4b1!4m9!3m8!1s0x304c407519a71a07:0x2213e8b0934ef03f!5m2!4m1!1i2!8m2!3d6.4172582!4d99.6970723!16s%2Fg%2F1hf5g54b1?entry=ttu",
        price: 1500,
        favourite: false,
        rating: 4.9,
        official_website: "https://www.thedatai.com/",
        description: "Nestled in the heart of a 10-million-year-old rainforest leading to an idyllic beach, The Datai Langkawi is a luxurious retreat offering an exquisite blend of nature and comfort. Experience world-class hospitality, stunning villas and suites, exceptional dining, and unique rainforest and beach activities, all within a pristine natural environment."
    },

    'the majestic hotel kuala lumpur': {
        category: "accomodation",
        link_name: "the majestic hotel kuala lumpur",
        name: "The Majestic Hotel Kuala Lumpur",
        image: "/the-majestic-hotel-kl.jpg",
        room_info: "Colonial-style rooms, butler service, award-winning dining, spa, swimming pool, cigar room",
        payment_info: "RM550/person",
        short_location: "Kuala Lumpur",
        location: "5 Jalan Sultan Hishamuddin, 50000 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia",
        location_link: "https://www.google.com/maps/place/The+Majestic+Hotel+Kuala+Lumpur/@3.1388147,101.6917637,17z/data=!3m1!4b1!4m6!3m5!1s0x31cc49e75525048d:0x39a044ce4a2d398f!8m2!3d3.1388147!4d101.6917637!16s%2Fg%2F11b6m70n0f?entry=ttu",
        price: 550,
        favourite: false,
        rating: 4.8,
        official_website: "https://www.majestic.com.my/",
        description: "A heritage landmark, The Majestic Hotel Kuala Lumpur combines colonial charm with modern luxury. Housed in a beautifully restored historical building, it offers elegant accommodation, exceptional culinary experiences including a famed tea lounge, and impeccable service, transporting guests back to the golden era of Malaysia."
    },

    'eastern & oriental hotel penang': {
        category: "accomodation",
        link_name: "eastern & oriental hotel penang",
        name: "Eastern & Oriental Hotel Penang",
        image: "/e-o-hotel-penang.jpg",
        room_info: "Heritage suites, sea views, outdoor pool, multiple restaurants, bar, fitness center",
        payment_info: "RM480/person",
        short_location: "Penang",
        location: "10 Lebuh Farquhar, 10200 George Town, Pulau Pinang, Malaysia",
        location_link: "https://www.google.com/maps/place/Eastern+%26+Oriental+Hotel/@5.4214539,100.342939,17z/data=!3m1!4b1!4m9!3m8!1s0x304ac21262d295ff:0x507567087610360a!5m2!4m1!1i2!8m2!3d5.4214539!4d100.342939!16s%2Fg%2F11b6m70n0f?entry=ttu",
        price: 480,
        favourite: false,
        rating: 4.7,
        official_website: "https://www.eohotels.com/",
        description: "The legendary Eastern & Oriental Hotel, affectionately known as the 'E&O', is a grand dame of heritage hotels in Penang. Overlooking the Andaman Sea, it offers luxurious all-suite accommodations, a timeless colonial ambiance, and unparalleled service, making it an iconic choice for a refined stay in George Town."
    },

    'pangkor laut resort': {
        category: "accomodation",
        link_name: "pangkor laut resort",
        name: "Pangkor Laut Resort",
        image: "/pangkor-laut-resort.jpg",
        room_info: "Private island resort, overwater villas, rainforest villas, multiple pools, spa village, fine dining",
        payment_info: "RM900/person",
        short_location: "Perak",
        location: "Pangkor Laut Island, 32200 Lumut, Perak Darul Ridzuan, Malaysia",
        location_link: "https://www.google.com/maps/place/Pangkor+Laut+Resort/@4.2057393,100.5694295,17z/data=!3m1!4b1!4m9!3m8!1s0x3034d396cbb7f341:0x2213e8b0934ef03f!5m2!4m1!1i2!8m2!3d4.2057393!4d100.5694295!16s%2Fg%2F11b6m70n0f?entry=ttu",
        price: 900,
        favourite: false,
        rating: 4.9,
        official_website: "https://www.pangkorlautresort.com/",
        description: "Pangkor Laut Resort is a private island paradise off the coast of Perak, offering a secluded and luxurious escape. With stunning overwater and rainforest villas, a world-renowned Spa Village, and pristine Emerald Bay, it promises an exclusive and unforgettable experience amidst nature's tranquility. 'One Island, One Resort'."
    },

    'lexis hibiscus port dickson': {
        category: "accomodation",
        link_name: "lexis hibiscus port dickson",
        name: "Lexis Hibiscus Port Dickson",
        image: "/lexis-hibiscus-pd.jpg",
        room_info: "Overwater villas with private pools, direct ocean access, multiple F&B outlets, spa, recreation activities",
        payment_info: "RM400/person",
        short_location: "Negeri Sembilan",
        location: "12th Mile, Jalan Pantai, Pasir Panjang, 71250 Port Dickson, Negeri Sembilan, Malaysia",
        location_link: "https://www.google.com/maps/place/Lexis+Hibiscus+Port+Dickson/@2.4704047,101.8906915,17z/data=!3m1!4b1!4m6!3m5!1s0x31cb92c287a950ed:0x2213e8b0934ef03f!8m2!3d2.4704047!4d101.8906915!16s%2Fg%2F11b6m70n0f?entry=ttu",
        price: 400,
        favourite: false,
        rating: 4.6,
        official_website: "https://www.lexishibiscus.com/",
        description: "Lexis Hibiscus Port Dickson is an iconic resort featuring unique overwater villas arranged in the shape of a hibiscus flower, each equipped with its own private plunge pool and steam room. It offers a luxurious and distinctive stay with direct access to the sea, perfect for families and couples seeking a memorable getaway on the coast."
    },


    'shangri-la rasa ria resort & spa kota kinabalu': {
        category: "accomodation",
        link_name: "shangri-la rasa ria resort & spa kota kinabalu",
        name: "Shangri-La Rasa Ria Resort & Spa, Kota Kinabalu",
        image: "/shangri-la-rasa-ria.jpg",
        room_info: "Luxury beachfront rooms/suites, private balconies, nature reserve with orangutan care, golf course, spa, multiple dining options, family activities",
        payment_info: "RM600/person",
        short_location: "Sabah",
        location: "Pantai Dalit Beach, Tuaran, 89200 Kota Kinabalu, Sabah, Malaysia",
        location_link: "https://www.google.com/maps/place/Shangri-La+Rasa+Ria,+Kota+Kinabalu/@6.1557008,116.2731876,17z/data=!3m1!4b1!4m9!3m8!1s0x323b26615b1427b3:0x1b8b6e06b94e0e8e!5m2!4m1!1i2!8m2!3d6.1557008!4d116.2731876!16s%2Fg%2F1hc35b71j?entry=ttu",
        price: 600,
        favourite: false,
        rating: 4.8,
        official_website: "https://www.shangri-la.com/kotakinabalu/rasaria/",
        description: "Set amidst a nature reserve, Shangri-La Rasa Ria offers a luxurious escape with a pristine beach and lush rainforest backdrop. Guests can enjoy world-class facilities, engage in wildlife encounters at the Rasa Ria Reserve, play golf, or simply relax by the pool, making it an ideal destination for nature lovers and families."
    },

    'g hotel gurney penang': {
        category: "accomodation",
        link_name: "g hotel gurney penang",
        name: "G Hotel Gurney, Penang",
        image: "/g-hotel-gurney.jpg",
        room_info: "Modern and stylish rooms, infinity pool, fitness center, multiple restaurants and bars, direct access to Gurney Plaza mall",
        payment_info: "RM320/person",
        short_location: "Penang",
        location: "168 Persiaran Gurney, George Town, 10250 George Town, Pulau Pinang, Malaysia",
        location_link: "https://www.google.com/maps/place/G+Hotel+Gurney/@5.437346,100.310185,17z/data=!3m1!4b1!4m6!3m5!1s0x304ac2465e900c43:0x1b43a5710dd9f67a!8m2!3d5.437346!4d100.310185!16s%2Fg%2F12h4m2q0t?entry=ttu",
        price: 320,
        favourite: false,
        rating: 4.6,
        official_website: "https://www.ghotel.com.my/gurney/",
        description: "G Hotel Gurney offers a stylish and contemporary stay right on Penang's famous Gurney Drive, providing direct access to premium shopping. With sleek design, comfortable rooms, and excellent facilities including an infinity pool, it's a perfect choice for both leisure and business travelers seeking modern comforts and convenience."
    },

    'aloft kuala lumpur sentral': {
        category: "accomodation",
        link_name: "aloft kuala lumpur sentral",
        name: "Aloft Kuala Lumpur Sentral",
        image: "/aloft-kl-sentral.jpg",
        room_info: "Loft-inspired rooms, rooftop infinity pool, WXYZ bar, 24/7 gym, direct link to KL Sentral transportation hub",
        payment_info: "RM250/person",
        short_location: "Kuala Lumpur",
        location: "5 Jalan Stesen Sentral, 50470 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia",
        location_link: "https://www.google.com/maps/place/Aloft+Kuala+Lumpur+Sentral/@3.1345995,101.6853243,17z/data=!3m1!4b1!4m6!3m5!1s0x31cc49e701980301:0x36484390f70a1841!8m2!3d3.1345995!4d101.6853243!16s%2Fg%2F11b6m70n0f?entry=ttu",
        price: 250,
        favourite: false,
        rating: 4.4,
        official_website: "https://www.marriott.com/en-us/hotels/kulal-aloft-kuala-lumpur-sentral/overview/",
        description: "Aloft Kuala Lumpur Sentral is a vibrant and modern hotel ideally connected to the city's main transportation hub, KL Sentral. It offers stylish, tech-savvy rooms, a lively WXYZ bar, and a stunning rooftop infinity pool, catering to the needs of modern travelers looking for convenience and a lively atmosphere."
    },

    'the banjaran hotsprings retreat ipoh': {
        category: "accomodation",
        link_name: "the banjaran hotsprings retreat ipoh",
        name: "The Banjaran Hotsprings Retreat, Ipoh",
        image: "/the-banjaran-hotsprings.jpg",
        room_info: "Luxury villas with private pools, natural hot springs, ice bath, meditation cave, geothermal lake, spa village, fine dining",
        payment_info: "RM1200/person",
        short_location: "Perak",
        location: "1 Persiaran Lagun Sunway 3, Sunway City Ipoh, 31150 Ipoh, Perak, Malaysia",
        location_link: "https://www.google.com/maps/place/The+Banjaran+Hotsprings+Retreat/@4.618685,101.127453,17z/data=!3m1!4b1!4m6!3m5!1s0x31cd3d4000000001:0x1b8b6e06b94e0e8e!8m2!3d4.618685!4d101.127453!16s%2Fg%2F11b6m70n0f?entry=ttu",
        price: 1200,
        favourite: false,
        rating: 4.9,
        official_website: "https://www.thebanjaran.com/",
        description: "An exclusive wellness retreat nestled within a lush valley, The Banjaran Hotsprings Retreat offers a unique adults-only experience with natural hot springs, stunning limestone caves, and luxurious villas. It's dedicated to holistic well-being, providing an unparalleled escape for relaxation, rejuvenation, and indulgence in nature's tranquility."
    },

    'hilton garden inn melaka': {
        category: "accomodation",
        link_name: "hilton garden inn melaka",
        name: "Hilton Garden Inn Melaka",
        image: "/hilton-garden-inn-melaka.jpg",
        room_info: "Modern rooms, rooftop infinity pool with city views, 24/7 fitness center, Garden Grille & Bar, complimentary WiFi",
        payment_info: "RM180/person",
        short_location: "Melaka",
        location: "2477 Jalan Tun Ali, 75300 Melaka, Malaysia",
        location_link: "https://www.google.com/maps/place/Hilton+Garden+Inn+Melaka/@2.2036499,102.2599727,17z/data=!3m1!4b1!4m6!3m5!1s0x31d1f04473852175:0x1b8b6e06b94e0e8e!8m2!3d2.2036499!4d102.2599727!16s%2Fg%2F11b6m70n0f?entry=ttu",
        price: 180,
        favourite: false,
        rating: 4.3,
        official_website: "https://www.hilton.com/en/hotels/mlihggi-hilton-garden-inn-melaka/",
        description: "Hilton Garden Inn Melaka offers modern comfort and convenience in the historic city. With spacious rooms, a refreshing rooftop infinity pool providing panoramic city views, and excellent dining options, it's a solid choice for travelers looking for a comfortable and well-equipped stay close to Melaka's attractions."
    }
};

module.exports = accomodations;