const destinations = {
    'kuantan 188': {
        category: "destination",
        link_name: "kuantan 188",
        name: "Kuantan 188",
        image: "/kuantan.jpg",
        idea: "Family Travel",
        duration: "3 Days",
        rating: "4.9", 
        short_location: "Pahang",
        location: "Jalan Besar, 25000 Kuantan, Pahang",
        location_link: "https://www.google.com/maps/place/kuantan+188+location/data=!4m2!3m1!1s0x31c8ba9c53ade317:0x85959d620830f43d?sa=X&ved=1t:155783&ictx=111",
        price: 100,
        favourite: false,
        description: "Kuantan 188, which stands proud on the banks of Kuantan River here, is not only the latest iconic landmark of Pahang’s first city, but also sets the night and weekend moods of Kuantan, the capital city of Pahang situated on the East Coast of Malaysia.",
        operating_hour: "10:00 AM - 10:00 PM"
    },

    'batu caves': {
        category: "destination",
        link_name: "batu caves",
        name: "Batu Caves",
        image: "/batu-caves.jpg",
        idea: "History Buffs",
        duration: "1 Days",
        rating: "4.7",
        short_location: "Selangor",
        location: "Gombak, 68100 Batu Caves, Selangor",
        location_link: "https://www.google.com/maps/place/Batu+Caves/@3.2374545,101.6839234,17z/data=!3m1!4b1!4m6!3m5!1s0x31cc470c8949a805:0xf2bfebb2b36f9ef9!8m2!3d3.2378844!4d101.6840385!16zL20vMHN5cDk?entry=ttu&g_ep=EgoyMDI1MDUyOC4wIKXMDSoASAFQAw%3D%3D",
        price: 90,
        favourite: false,
        description: "Batu Caves is a famous Hindu temple complex located just north of Kuala Lumpur, Malaysia. Set within a series of limestone caves, it is best known for its towering golden statue of Lord Murugan and the 272 colorful steps leading up to the main Temple Cave. The site attracts pilgrims and tourists alike, especially during the Thaipusam festival. Visitors can explore the impressive caves, admire Hindu shrines, spot monkeys, and enjoy scenic views from the top. It's a unique cultural and natural landmark that offers both spiritual insight and adventure.",
        operating_hour: "10:00 AM - 9:00 PM"
    },

    'pulau tioman': {
        category: "destination",
        link_name: "pulau tioman",
        name: "Pulau Tioman",
        image: "/pulau-tioman.jpg",
        idea: "Natural Photography",
        duration: "5 Days",
        rating: "5.0",
        short_location: "Johor",
        location: "Pulau Tioman, Mersing, Johor",
        location_link: "https://www.google.com/maps/place/pulau+tioman+address/data=!4m2!3m1!1s0x31c51b92f94cd239:0xb7b7e438fc01e28e?sa=X&ved=1t:155783&ictx=111",
        price: 290,
        favourite: false,
        description: "Tioman Island lies off the east coast of Peninsular Malaysia, in the South China Sea. It's a nature reserve, ringed by beaches. The area is known for its dive sites, which have corals, sea fans and sea sponges, as well as shipwrecks. The island is covered in tropical rainforests, home to butterflies, lizards and monkeys. On the east coast, the Juara Turtle Project is a hatchery that protects and studies sea turtles",
        operating_hour: "10:00 AM - 10:00 PM"
    },

    'legoland malaysia resort': {
        category: "destination",
        link_name: "legoland malaysia resort",
        name: "Legoland Malaysia Resort",
        image: "/legoland-malaysia-resort.jpg",
        idea: "Family Travel",
        duration: "4 Days",
        rating: "5.0",
        short_location: "Johor",
        location: "7 Jalan Legoland, Johor Bahru 79250 Malaysia",
        location_link: "https://www.tripadvisor.com.my/Attraction_Review-g298278-d3491018-Reviews-Legoland_Malaysia-Johor_Bahru_Johor_Bahru_District_Johor.html#:~:text=7%20Jalan%20Legoland%2C%20Johor%20Bahru%2079250%20Malaysia",
        price: 130,
        favourite: false,
        description: "LEGOLAND Malaysia Resort in Iskandar Puteri, Johor, is a family-friendly destination with over 80 rides, shows, and attractions. It's the first LEGOLAND theme park in Asia and the sixth in the world, offering a unique blend of amusement park fun with LEGO theming. ",
        operating_hour: "10:00 AM - 6:00 PM"
    },

    'kek lok si temple': {
        category: "destination",
        link_name: "kek lok si temple",
        name: "Kek Lok Si Temple",
        image: "/Kek-Lok-Si-Temple-Penang.jpg",
        idea: "Cultural Lover",
        duration: "1 Days",
        rating: "4.6",
        short_location: "Penang",
        location: "Jln Balik Pulau, 11500 Ayer Itam, Pulau Pinang",
        location_link: "https://www.google.com/maps/place/kek+lok+si+temple/data=!4m2!3m1!1s0x304ac2185dfc8665:0x2c9084ea7f433ec4?sa=X&ved=1t:155783&ictx=111",
        price: 40,
        favourite: false,
        description: "The Kek Lok Si Temple is a Buddhist temple in George Town in the Malaysian state of Penang. Located at Ayer Itam, it is the largest Buddhist temple in Malaysia and an important pilgrimage centre for Buddhists from Hong Kong, the Philippines, Singapore and other parts of Southeast Asia.",
        operating_hour: "8.30 AM - 5.30 PM"
    },

    'aquaria klcc': {
        category: "destination",
        link_name: "aquaria klcc",
        name: "Aquaria KLCC",
        image: "/aquaria_klcc.jpg",
        idea: "Curious learners",
        duration: "1 Days",
        rating: "4.9",
        short_location: "Kuala Lumpur",
        location: "Kuala Lumpur City Centre, 50088 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur",
        location_link: "https://www.google.com/maps/place/aquaria+klcc/data=!4m2!3m1!1s0x31cc37d39d319733:0x68a27ec3fd8f6bed?sa=X&ved=1t:155783&ictx=111",
        price: 229,
        favourite: false,
        description: "The Aquaria KLCC is an oceanarium located beneath Kuala Lumpur Convention Centre within Kuala Lumpur City Centre in Kuala Lumpur, Malaysia.",
        operating_hour: "10:00 AM - 10:00 PM"
    },

    'pulau langkawi': {
        category: "destination",
        link_name: "pulau langkawi",
        name: "Pulau Langkawi",
        image: "/langkawi.png",
        idea: "Curious learners",
        duration: "5 Days",
        rating: "4.6",
        short_location: "Kedah",
        location: "07000 Langkawi",
        location_link: "https://www.google.com/maps/place/pulau+langkawi+location/data=!4m2!3m1!1s0x304c78da69c4755d:0xe43971dbd7bd6dfe?sa=X&ved=1t:155783&ictx=111",
        price: 119,
        favourite: false,
        description: "Langkawi, officially known as Langkawi, the Jewel of Kedah, is a duty-free island and an archipelago of 99 islands located some 30 km off the coast of northwestern Malaysia and a few kilometres south of Ko Tarutao.",
        operating_hour: "11:00 AM - 10:30 PM"
    },

    'cenang beach': {
        category: "destination",
        link_name: "cenang beach",
        name: "Cenang Beach",
        image: "/cenang-beach.jpg",
        idea: "Family Travel",
        duration: "3 Days",
        rating: "4.2",
        short_location: "Kedah",
        location: "07000, Kedah",
        location_link: "https://www.google.com/maps/place/Pantai+Cenang/@6.291916,99.7137643,15z/data=!3m1!4b1!4m6!3m5!1s0x304b880ba2f7821b:0xc3f05608f5876103!8m2!3d6.2955916!4d99.7228132!16s%2Fg%2F1q5blf90y?entry=ttu&g_ep=EgoyMDI1MDYxNy4wIKXMDSoASAFQAw%3D%3D",
        price: 239,
        favourite: false,
        description: "Pantai Cenang, also known as Cenang Beach, is a popular beach destination in Langkawi, Malaysia. It's known for its long stretch of sandy shore, vibrant atmosphere, and array of activities. The beach offers a mix of relaxation and excitement, with opportunities for swimming, sunbathing, and various water sports. ",
        operating_hour: "6:00 AM - 10:30 PM"
    },

    'laman padi langkawi': {
        category: "destination",
        link_name: "laman padi langkawi",
        name: "Laman Padi Langkawi",
        image: "/laman-padi-langkawi.jpg",
        idea: "Educational Outings",
        duration: "1 Days",
        rating: "4.1",
        short_location: "Kedah",
        location: "Pantai Cenang, 07000 Langkawi, Kedah",
        location_link: "https://www.google.com/maps/place/laman+padi+langkawi/data=!4m2!3m1!1s0x304b880a9a7d167f:0xf61d8b74a16faf2b?sa=X&ved=1t:155783&ictx=111",
        price: 105,
        favourite: false,
        description: "Open-air museum exploring the history of rice cultivation, with guided tours & hands-activities.",
        operating_hour: "10:00 AM - 10:30 PM"
    },

    'langkawi sky bridge': {
        category: "destination",
        link_name: "langkawi sky bridge",
        name: "Langkawi Sky Bridge",
        image: "/langkawi-sky-bridge.jpg",
        idea: "Birdwatching",
        duration: "1 Days",
        rating: "4.1",
        short_location: "Kedah",
        location: "07000 Langkawi, Kedah",
        location_link: "https://www.google.com/maps/place/langkawi+sky+bridge/data=!4m2!3m1!1s0x304c76c41c936fc3:0x36f2796db82629c3?sa=X&ved=1t:155783&ictx=111",
        price: 100,
        favourite: false,
        description: "Langkawi Sky Bridge is a 125-metre curved pedestrian cable-stayed bridge in Malaysia, completed in 2005. The bridge deck is 660 metres above sea level at the peak of Gunung Mat Cincang on Pulau Langkawi, the main island of the Langkawi archipelago in Kedah.",
        operating_hour: "8:30 AM - 6:30 PM"
    },

    'oriental village': {
        category: "destination",
        link_name: "oriental village",
        name: "Oriental Village",
        image: "/oriental-village.jpg",
        idea: "Birdwatching",
        duration: "1 Days",
        rating: "4.4",
        short_location: "Kedah",
        location: "07000 Langkawi, Kedah",
        location_link: "https://www.google.com/maps/place/Oriental+Village/data=!4m2!3m1!1s0x304c76e4c9afffff:0x1d286d90cf737d1e?sa=X&ved=1t:155783&ictx=111",
        price: 49,
        favourite: false,
        description: "The Oriental Village is an open-air themed village complex designed to give visitors an all-inclusive experience all inone place. The village is designed around a central lake and various attractions are located close by. The sheer assortment of activities at the oriental village demands a whole day of exploring to enjoy them.",
        operating_hour: "8:30 AM - 6:30 PM"
    },

    'wat mai suwankiri': {
        category: "destination",
        link_name: "wat mai suwankiri",
        name: "Wat Mai Suwankiri",
        image: "/wat-mai-sunwankiri.jpg",
        idea: "Cultural Lover",
        duration: "1 Days",
        rating: "4.6",
        short_location: "Kelantan",
        location: "16200 Tumpat, Kelantan",
        location_link: "https://www.google.com/maps/place/Wat+Mai+Suwankiri/data=!4m2!3m1!1s0x0:0xdd52b2058d74ae07?sa=X&ved=1t:2428&ictx=111",
        price: 32,
        favourite: false,
        description: "Compared to the other Thai temples in Tumpat, there's actually more to see. The hall of the dragon boat has some nice murals and the most has fishes. The other hall had a really impressive Buddha statue. One thing, the access road can be very narrow and steep.",
        operating_hour: "8:30 AM - 6:30 PM"
    },

    'street art kota bharu': {
        category: "destination",
        link_name: "street art kota bharu",
        name: "Street Art Kota Bharu",
        image: "/street-art-kota-bharu.jpg",
        idea: "Natural Photography",
        duration: "1 Days",
        rating: "5.0",
        short_location: "Kelantan",
        location: "15000 Kota Bharu, Kelantan",
        location_link: "https://www.google.com/maps/place/Street+Art+Kota+Bharu/data=!4m2!3m1!1s0x0:0x56fcde92f5a2b33c?sa=X&ved=1t:2428&ictx=111",
        price: 32,
        favourite: false,
        description: "Amazing street art murals. The best we have seen in our travels all over Malaysia. Near Pasar Siti Khadijah. Beautiful imagery of Malaysia customs, food and everyday life spread over several laneways. Just walk down some backstreets in the area.",
        operating_hour: "8:30 AM - 11:59 PM"
    },

    'island of tioman': {
        category: "destination",
        link_name: "island of tioman",
        name: "Island of Tioman",
        image: "/island-of-tioman.png",
        idea: "Curious learners",
        duration: "2 Days",
        rating: "4.3",
        short_location: "Pahang",
        location: "Mersing, Pahang",
        location_link: "https://www.google.com/maps/place/Tioman+Island/@2.8064825,104.1703345,12z/data=!3m1!4b1!4m6!3m5!1s0x31c51b92f94cd239:0xb7b7e438fc01e28e!8m2!3d2.7902494!4d104.1698463!16zL20vMDFubWIx?entry=ttu&g_ep=EgoyMDI1MDYwMS4wIKXMDSoASAFQAw%3D%3D",
        price: 150,
        favourite: false,
        description: "Tioman Island lies off the east coast of Peninsular Malaysia, in the South China Sea. It's a nature reserve, ringed by beaches. The area is known for its dive sites, which have corals, sea fans and sea sponges, as well as shipwrecks. The island is covered in tropical rainforests, home to butterflies, lizards and monkeys. On the east coast, the Juara Turtle Project is a hatchery that protects and studies sea turtles. ",
        operating_hour: "11:00 AM - 10:30 PM"
    },

    'genting highland': {
        category: "destination",
        link_name: "genting highland",
        name: "Genting Highland",
        image: "/genting_highland.jpg",
        idea: "Family Travel",
        duration: "2 Days",
        rating: "4.9", 
        short_location: "Pahang",
        location: "Genting Highlands, 69000 Genting Highlands, Pahang",
        location_link: "https://www.google.com/maps/place/Genting+Highlands,+Pahang/@3.3981172,101.7832129,13z/data=!3m1!4b1!4m6!3m5!1s0x31cc14067e9a39c3:0x1b8edcdc4d5bf56!8m2!3d3.423978!4d101.7932011!16s%2Fg%2F11bc5hs7tr?entry=ttu&g_ep=EgoyMDI1MDUyOC4wIKXMDSoASAFQAw%3D%3D",
        price: 200,
        favourite: false,
        description: "Genting Highlands is a hill station located on the peak of Mount Ulu Kali in the Titiwangsa Mountains, central Peninsular Malaysia, at 1800 metres elevation. Located in the state of Pahang, it was established in 1965 by the late Malaysian businessman Lim Goh Tong. The primary tourist attraction is Resorts World Genting, a hill resort where casinos and theme parks are situated and where gambling is permitted. Many of Pahang's skyscrapers can be found here.",
        operating_hour: "10:00 AM - 10:00 PM"
    },

    'kuala gandah elephant': {
        category: "destination",
        link_name: "kuala gandah elephant",
        name: "Kuala Gandah Elephant",
        image: "/kuala-gandah-elephant.jpg",
        idea: "Green Lifestyle Enthusiasts",
        duration: "1 Days",
        rating: "4.5", 
        short_location: "Pahang",
        location: "Jln Bolok - Mempaga, 28500 Malaysia",
        location_link: "https://www.google.com/maps/search/kuala+gandah+elephant+location/@3.5914733,102.1435189,17z?entry=ttu&g_ep=EgoyMDI1MDUyOC4wIKXMDSoASAFQAw%3D%3D",
        price: 80,
        favourite: false,
        description: "You'll never forget the day you helped give an elephant a bath (additional request with the help of a guide). Currently elephant riding has been temporary stopped until further notice. Get up close and personal with the amazing semi-wild elephants at Kuala Gandah Elephant Sanctuary. Be sure to book in advance because the center has strict daily visitor quotas",
        operating_hour: "10:30 AM - 6:30 PM"
    },

    'cameron highland': {
        category: "destination",
        link_name: "cameron highland",
        name: "Cameron Highland",
        image: "/cameron-highland.jpg",
        idea: "Green Lifestyle Enthusiasts",
        duration: "3 Days",
        rating: "4.6", 
        short_location: "Pahang",
        location: "Brinchang, 39100 Brinchang, Pahang",
        location_link: "https://www.google.com/maps/place/cameron+highland+location/data=!4m2!3m1!1s0x31ca5082fa7f0d47:0x655625f6e1faf2f4?sa=X&ved=1t:155783&ictx=111",
        price: 280,
        favourite: false,
        description: "The Cameron Highlands are a popular hill station and tourist destination in Peninsular Malaysia, located within the state of Pahang. It's known for its cool climate, tea plantations, strawberry farms, and other agricultural activities. The area is also known for its natural beauty and is a popular destination for those seeking a relaxing getaway. ",
        operating_hour: "10:30 AM - 6:30 PM"
    },

    'teluk chempedak': {
        category: "destination",
        link_name: "teluk chempedak",
        name: "Teluk Chempedak",
        image: "/teluk-chempedak.jpeg",
        idea: "Green Lifestyle Enthusiasts",
        duration: "1 Days",
        rating: "4.3", 
        short_location: "Pahang",
        location: "25050, Pahang",
        location_link: "https://www.google.com/maps/place/Teluk+Cempedak/@3.8097741,103.3728364,16z/data=!3m1!4b1!4m6!3m5!1s0x31c8a5450ef61e89:0x8465bfd2f01c4578!8m2!3d3.8119576!4d103.3725871!16s%2Fm%2F02pz68k?entry=ttu&g_ep=EgoyMDI1MDUyOC4wIKXMDSoASAFQAw%3D%3D",
        price: 120,
        favourite: false,
        description: "Teluk Cempedak or Teluk Chempedak also known as Palm Beach is a beach in Kuantan, Pahang, Malaysia. It is located 5 kilometres east from the town centre in Kuantan. The white sandy beach and casuarinas and pine trees line the coast, with some rocky promontories facing the South China Sea.",
        operating_hour: "5:30 AM - 10:30 PM"
    },

'sunway lagoon': {
        category: "destination",
        link_name: "sunway lagoon",
        name: "Sunway Lagoon",
        image: "/sunway-lagoon.jpg",
        idea: "Family Travel",
        duration: "4 Days",
        rating: "4.8",
        short_location: "Selangor",
        location: "No 3, Jalan PJS 11/11 Bandar Sunway, Petaling Jaya 47500 Malaysia",
        location_link: "https://www.google.com/maps/place/sunway+lagoon+location/data=!4m2!3m1!1s0x31cc4c88dded3125:0xdb654cc77af0cdbc?sa=X&ved=1t:155783&ictx=111",
        price: 390,
        favourite: false,
        description: "Malaysia's premier multi-park destination offers more than 90 attractions across its six parks - Amusement Park, Water Park, Wildlife Park, Extreme Park, Scream Park, and Asia's First Nickelodeon Themed Land, Nickelodeon Lost Lagoon! Once you step in, you can spend the entire day here! Explore the various Dining options available at the theme park. If you need some place to sleep, we are just next door to the Sunway Resort Hotel & Spa. We also play host to some of the hottest acts and global events so stay tuned for upcoming events and promotion.",
        operating_hour: "10:00 AM - 6:00 PM"
    },

    'thai chetawan temple': {
        category: "destination",
        link_name: "thai chetawan temple",
        name: "Thai Chetawan Temple",
        image: "/thai-chetawan-temple.jpg",
        idea: "History Buffs",
        duration: "1 Days",
        rating: "4.8",
        short_location: "Selangor",
        location: "No.24, Jalan Pantai 9/7 Off Jalan Gasing, Petaling Jaya 46000 Malaysia",
        location_link: "https://www.google.com/maps/place/thai+chetawan+temple/data=!4m2!3m1!1s0x31cc4bcfde68dab3:0x44d3fc65e1c3399e?sa=X&ved=1t:155783&ictx=111",
        price: 89,
        favourite: false,
        description: "A truly remarkable Thai Buddhist Temple in the heart of Petaling Jaya. A wonderful temple that offers a great solace to those seeking some peace and quiet. A good place to offer prayers and mediate.",
        operating_hour: "9:00 AM - 5:30 PM"
    },

    'sultan salahuddin abdul aziz shah mosque': {
        category: "destination",
        link_name: "sultan salahuddin abdul aziz shah mosque",
        name: "Sultan Salahuddin Abdul Aziz Shah Mosque",
        image: "/sultan-salahuddin-abdul-aziz-shah-mosque.jpg",
        idea: "History Buffs",
        duration: "1 Days",
        rating: "5.0",
        short_location: "Selangor",
        location: "Persiaran Masjid St. Sekysen 14, Shah Alam 40000 Malaysia",
        location_link: "https://www.tripadvisor.com.my/Attraction_Review-g298316-d1632410-Reviews-Sultan_Salahuddin_Abdul_Aziz_Shah_Mosque-Shah_Alam_Petaling_District_Selangor.html#:~:text=Persiaran%20Masjid%20St.%20Sekysen%2014%2C%20Shah%20Alam%2040000%20Malaysia",
        price: 70,
        favourite: false,
        description: "The biggest masjid in Malaysia which is less than 1 hour drive away from KL. It is very clean, stunning, amazing Islamic architecture, beautiful viewpoints, and very big. This is a must visit if you are staying in KL. Personally think this Blue Mosque is better than the one in Istanbul.",
        operating_hour: "9:00 AM - 6:00 PM"
    },

    'farm in the city': {
        category: "destination",
        link_name: "farm in the city",
        name: "Farm In The City",
        image: "/farm-in-the-city.jpg",
        idea: "Birdwatching",
        duration: "1 Days",
        rating: "5.0",
        short_location: "Selangor",
        location: "Persiaran Masjid St. Sekysen 14, Shah Alam 40000 Malaysia",
        location_link: "https://www.tripadvisor.com.my/Attraction_Review-g298316-d1632410-Reviews-Sultan_Salahuddin_Abdul_Aziz_Shah_Mosque-Shah_Alam_Petaling_District_Selangor.html#:~:text=Persiaran%20Masjid%20St.%20Sekysen%2014%2C%20Shah%20Alam%2040000%20Malaysia",
        price: 179,
        favourite: false,
        description: "Farm in the City (FITC) is an unique concept that combines the elements of wildlife and nature set in a designed environment of a conservation park. resembling a typical Malaysian Village setting, it houses more than 100 species of Farm and Exotic animals and plants in specially built enclosures. One can get close, touch or feed the animals with almost Zero distance.",
        operating_hour: "9:00 AM - 6:00 PM"
    },

'johor bahru city square': {
        category: "destination",
        link_name: "johor bahru city square",
        name: "Johor Bahru City Square",
        image: "/johor-bahru-city-square.jpg",
        idea: "Eco-conscious Shoppers",
        duration: "1 Days",
        rating: "4.4",
        short_location: "Johor",
        location: "106-108 Jalan Wong Ah Fook, Johor Bahru 80000 Malaysia",
        location_link: "https://www.tripadvisor.com.my/Attraction_Review-g298278-d457057-Reviews-Johor_Bahru_City_Square-Johor_Bahru_Johor_Bahru_District_Johor.html#:~:text=106%2D108%20Jalan%20Wong%20Ah%20Fook%2C%20Johor%20Bahru%2080000%20Malaysia",
        price: 199,
        favourite: false,
        description: "Strategically located in the heart of the city and only a stone's throw from the customs and immigration checkpoint, Johor Bahru City Square stands out as a central landmark in JB. With its more than 200 retailers, it offers a host of fashion, entertainment and restaurants. All catered to wow the senses and satisfy the needs. Rush in when the doors open at 10am for breakfast, then head out and start your shopping adventure of clothes, shoes, bags, trinklets, toiletries, electronic toys. Everything the heart desires. Unique to Johor Bahru City Square is the Inner City, an eclectic mix of smallish fashion and accessory shops plus restaurants housed in a tight, quaint setting. Always a firm favorite of the now generation. After many hours of shopping, rest the feet in one of the numerous restaurants and cafes or indulge in a soothing foot massage, then go on to treat the rest of the body at a salon.",
        operating_hour: "10:00 AM - 10:00 PM"
    },

    'pulai waterfall': {
        category: "destination",
        link_name: "pulai waterfall",
        name: "Pulai Waterfall",
        image: "/pulai-waterfall.jpg",
        idea: "Green Lifestyle Enthusiasts",
        duration: "1 Days",
        rating: "4.7",
        short_location: "Johor",
        location: "Gunung Pulai Recreational Forest, Johor Bahru 81000 Malaysia",
        location_link: "https://www.tripadvisor.com.my/Attraction_Review-g298278-d457113-Reviews-Pulai_Waterfall-Johor_Bahru_Johor_Bahru_District_Johor.html#:~:text=Gunung%20Pulai%20Recreational%20Forest%2C%20Johor%20Bahru%2081000%20Malaysia",
        price: 110,
        favourite: false,
        description: "Pulai Waterfall offers a good experience with available changing and bathing facilities, unlike Kota Tinggi falls. Notably, Pulai Waterfall has no fishes. This suggests it might be a more pleasant swimming experience for those who prefer it. The lack of fish could also indicate differences in the ecosystem or water quality compared to other waterfalls in the area.",
        operating_hour: "8:00 AM - 5:00 PM"
    },

    'arulmigu sri rajakaliamman glass temple': {
        category: "destination",
        link_name: "arulmigu sri rajakaliamman glass temple",
        name: "Arulmigu Sri Rajakaliamman Glass Temple",
        image: "/arulmigu-sri-rajakaliamman.jpg",
        idea: "History Buffs",
        duration: "1 Days",
        rating: "4.8",
        short_location: "Johor",
        location: "Jalan Tun Abdul Razak 1/1, Wadi Hana, 80300 Johor Bahru",
        location_link: "https://www.google.com/maps/place/Arulmigu+Sri+Rajakaliamman+Glass+Temple/data=!4m2!3m1!1s0x31da12cf69335e0f:0xbfde6877a54a647b?sa=X&ved=1t:155783&ictx=111",
        price: 40,
        favourite: false,
        description: "The Arulmigu Sri Rajakaliamman Glass Temple is a Hindu temple in Johor Bahru, Johor, Malaysia. It is also one of the state's tourist attractions. The temple was listed in the Malaysian Book of Records as the first and only glass temple in the nation on 12 May 2010.",
        operating_hour: "7:00 AM - 12:00 PM"
    },

'the habitat penang hill': {
        category: "destination",
        link_name: "the habitat penang hill",
        name: "The Habitat Penang Hill",
        image: "/the-habitat-penang-hill.jpg",
        idea: "Relaxing Walk",
        duration: "2 Days",
        rating: "4.8",
        short_location: "Penang",
        location: "Bukit Bendera, Penang Island 11300 Malaysia",
        location_link: "https://www.tripadvisor.com.my/Attraction_Review-g660694-d9785744-Reviews-The_Habitat_Penang_Hill-Penang_Island_Penang.html#:~:text=Bukit%20Bendera%2C%20Penang%20Island%2011300%20Malaysia",
        price: 30,
        favourite: false,
        description: "The Habitat Penang Hill provides the most authentic, diverse and educational Malaysian rainforest experience. Reconnect with nature in its purest form as you immerse yourself in our 130-million year old rainforest. Starting at the forest floor, our Naturalists will take you on a journey along our Nature Trail to explore the myriad of flora and fauna – plants, trees, insects, birds, reptiles, and mammals that call The Habitat home. Explore the biodiversity of the rainforest canopy on our 230m Langur Way Canopy Walk. Visit Curtis Crest Tree Top Walk at the top of Penang Hill, and embrace the 360-degree panoramic views of Penang Island from the highest viewing point of Penang. ",
        operating_hour: "9:00 AM - 7:00 PM"
    },

    'entopia': {
        category: "destination",
        link_name: "entopia",
        name: "Entopia",
        image: "/entopia.jpg",
        idea: "Green Lifestyle Enthusiasts",
        duration: "1 Days",
        rating: "4.8",
        short_location: "Penang",
        location: "830 Jalan Teluk Bahang, Teluk Bahang, Penang Island 11050 Malaysia",
        location_link: "https://www.tripadvisor.com.my/Attraction_Review-g4975755-d457111-Reviews-Entopia-Teluk_Bahang_Penang_Island_Penang.html#:~:text=830%20Jalan%20Teluk%20Bahang%2C%20Teluk%20Bahang%2C%20Penang%20Island%2011050%20Malaysia",
        price: 72,
        favourite: false,
        description: "Entopia, a tropical sanctuary for our planet's little denizens from those that fly freely in the sky to the ones that creep stealthily beneath the ground. Journey into a magical paradise that honours the unsung heroes of our natural world with plenty to discover from outdoor adventures to cavernous mysteries and a multi-storey Indoor Discovery Centre. Live the moment with exciting interactive workshops and activities.",
        operating_hour: "9:00 AM - 7:00 PM"
    },

    'pinang peranakan mansion': {
        category: "destination",
        link_name: "pinang peranakan mansion",
        name: "Pinang Peranakan Mansion",
        image: "/pinang-peranakan-mansion.jpg",
        idea: "Educational Outings",
        duration: "1 Days",
        rating: "4.8",
        short_location: "Penang",
        location: "29, Church St, Georgetown, 10200 George Town, Penang",
        location_link: "https://www.google.com/maps/place/Pinang+Peranakan+Mansion/data=!4m2!3m1!1s0x304ac38fdcf36b09:0x8b7cdd7809de1be6?sa=X&ved=1t:155783&ictx=111",
        price: 72,
        favourite: false,
        description: "The Pinang Peranakan Mansion in George Town, Penang, Malaysia, is a museum dedicated to Penang's Peranakan heritage. The museum itself is housed within a distinctive green-hued mansion at Church Street, George Town, which once served as the residence and office of a 19th-century Chinese tycoon, Chung Keng Quee.",
        operating_hour: "9:00 AM - 7:00 PM"
    },

    'tropical spice garden': {
        category: "destination",
        link_name: "tropical spice garden",
        name: "Tropical Spice Garden",
        image: "/tropical-spice-garden.jpg",
        idea: "Birdwatching",
        duration: "1 Days",
        rating: "4.8",
        short_location: "Penang",
        location: "11050 George Town, Pulau Pinang",
        location_link: "https://www.google.com/maps/dir//Lot+595+Mukim,+2,+Jalan+Teluk+Bahang,+Teluk+Bahang,+11050+George+Town,+Pulau+Pinang/@5.4634825,100.1469378,12z/data=!4m8!4m7!1m0!1m5!1m1!1s0x304ae85e96b144b7:0xcf0985dd436d531b!2m2!1d100.2293398!2d5.4634881?entry=ttu&g_ep=EgoyMDI1MDYxNy4wIKXMDSoASAFQAw%3D%3D",
        price: 72,
        favourite: false,
        description: "Tropical Spice Garden is an eco-attraction tucked within a natural valley fronting the Straits of Malacca. The showcase garden houses over 500 species of herb, spice and tropical plants. Explore and discover the fabulous diversity of nature as you through trails and pathways that meander through undulating hills, jungles terraces and natural streams. ",
        operating_hour: "10:00 AM - 7:30 PM"
    },

    'lost world of tambun': {
        category: "destination",
        link_name: "lost world of tambun",
        name: "Lost World of Tambun",
        image: "/lost-world-of-tambun.jpg",
        idea: "Family Travel",
        duration: "2 Days",
        rating: "4.8",
        short_location: "Perak",
        location: "No. 1 Persiaran Lagun Sunway 1, Ipoh 31150 Malaysia",
        location_link: "https://www.tripadvisor.com.my/Attraction_Review-g298298-d1488280-Reviews-Lost_World_Of_Tambun-Ipoh_Kinta_District_Perak.html#:~:text=No.%201%20Persiaran%20Lagun%20Sunway%201%2C%20Ipoh%2031150%20Malaysia",
        price: 79,
        favourite: false,
        description: "The little world of big adventures, Sunway Lost World of Tambun is Malaysia’s premiere action and adventure family holiday destination in Ipoh, Malaysia. A theme park located in the historic town of Ipoh, in the middle of the North-South corridor in Perak; and is set in the natural landscapes of Ipoh, surrounded by exquisitely breath-taking limestone features. Whether it’s a weekend of mayhem oozing with family fun or a burst of eco-adventure that you’re seeking, take it all in as you journey through the attractions of the Lost World of Tambun.",
        operating_hour: "9:00 AM - 7:00 PM"
    },

    'pangkor island': {
        category: "destination",
        link_name: "pangkor island",
        name: "Pangkor Island",
        image: "/pangkor-island.jpeg",
        idea: "Family Travel",
        duration: "5 Days",
        rating: "5.0",
        short_location: "Perak",
        location: "Strait of Malacca",
        location_link: "https://www.google.com/maps/place/Pangkor+Island/data=!4m2!3m1!1s0x3034d396cbb7f341:0xc8f2ba9f74ec3895?sa=X&ved=1t:155783&ictx=111",
        price: 72,
        favourite: false,
        description: "Pangkor Island lies just off the west coast of Peninsular Malaysia. It’s known for beaches like Teluk Nipah, Coral Bay and Pasir Giam, which connects to coral-ringed Giam Island at low tide. Dating back to 1670, the ruined Dutch Fort demonstrates the island’s strategic colonial importance. Nearby, the Sacred Rock is inscribed with the Dutch East India Company symbol and a picture of a tiger carrying away a child",
        operating_hour: "9:00 AM - 7:00 PM"
    },

    'kellie castle': {
        category: "destination",
        link_name: "kellie castle",
        name: "Kellie Castle",
        image: "/kellie-castle.jpg",
        idea: "Educational Outings",
        duration: "5 Days",
        rating: "5.0",
        short_location: "Perak",
        location: "Lot 48436, Kompleks Pelancongan Kellie's Castle,, Batu Gajah 31000 Malaysia",
        location_link: "https://www.tripadvisor.com.my/Attraction_Review-g1450229-d1421132-Reviews-Kellie_s_Castle-Batu_Gajah_Kinta_District_Perak.html#:~:text=Lot%2048436%2C%20Kompleks%20Pelancongan%20Kellie%27s%20Castle%2C%2C%20Batu%20Gajah%2031000%20Malaysia",
        price: 60,
        favourite: false,
        description: "Kellie’s Castle: A historic gem in Perak, showcasing unique Moorish, Indian, and Romanesque architecture.",
        operating_hour: "9:30 AM - 6:00 PM"
    },

    'petronas twin tower': {
        category: "destination",
        link_name: "petronas twin tower",
        name: "Petronas Twin Tower",
        image: "/show-case-1.jpeg",
        idea: "Family Travel",
        duration: "7 Days",
        rating: "4.8",
        short_location: "Kuala Lumpur",
        location: "Concourse Level, Lower Ground Kuala Lumpur City Centre, Kuala Lumpur 50088 Malaysia",
        location_link: "https://www.tripadvisor.com.my/Attraction_Review-g298570-d317521-Reviews-Petronas_Twin_Towers-Kuala_Lumpur_Wilayah_Persekutuan.html#:~:text=Concourse%20Level%2C%20Lower%20Ground%20Kuala%20Lumpur%20City%20Centre%2C%20Kuala%20Lumpur%2050088%20Malaysia",
        price: 360,
        favourite: false,
        description: "No trip to KL would be complete without a visit to the world's tallest twin towers. The skyscrapers are utterly stunning, particularly when illuminated at night. The Twin Towers Visit Operations is open Tuesday through Sunday and tickets are released at 8:30 a.m. on a first-come, first-served basis. To avoid disappointment, you can purchase your ticket in advance via online ticketing or at the Ticketing Counter, Concourse Level.",
        operating_hour: "9:30 AM - 6:00 PM"
    },

    'pavilion kuala lumpur': {
        category: "destination",
        link_name: "pavilion kuala lumpur",
        name: "Pavilion Kuala Lumpur",
        image: "/pavilion-kl.jpg",
        idea: "Eco-conscious Shoppers",
        duration: "7 Days",
        rating: "4.8",
        short_location: "Kuala Lumpur",
        location: "168 Jalan Bukit Bintang, Kuala Lumpur 55100 Malaysia",
        location_link: "https://www.tripadvisor.com.my/Attraction_Review-g298570-d317521-Reviews-Petronas_Twin_Towers-Kuala_Lumpur_Wilayah_Persekutuan.html#:~:text=Concourse%20Level%2C%20Lower%20Ground%20Kuala%20Lumpur%20City%20Centre%2C%20Kuala%20Lumpur%2050088%20Malaysia",
        price: 120,
        favourite: false,
        description: "Pavilion Kuala Lumpur is an award-winning shopping mall located in the heart of Bukit Bintang, Malaysia’s shopping paradise. Pavilion Kuala Lumpur brings the best of retail with a nett lettable area of over 1.7 million square feet, 700 stores and 8 themed precincts. The Pavilion Crystal Fountain, a symbol of Malaysia’s diverse culture welcomes visitors to this tourist-friendly destination, surrounded by upmarket hotels and a 10-minute walk from KLCC. Enjoy tourist-centric services such as money changers, ATM machines, currency exchange kiosks, as well as specially curated tours for large groups.",
        operating_hour: "10:00 AM - 10:00 PM"
    },

'zoo negara kl': {
        category: "destination",
        link_name: "zoo negara kl",
        name: "Zoo Negara KL",
        image: "/Zoo-Negara-KL.jpeg",
        idea: "Curious learners",
        duration: "1 Days",
        rating: "4.9",
        short_location: "Kuala Lumpur",
        location: "Jalan Taman Zooview, Taman Zooview, 68000 Ampang, Selangor",
        location_link: "https://www.google.com/maps/place/zoo+negara+kl/data=!4m2!3m1!1s0x31cc39b60a831fe1:0xf2c800c702db7b2f?sa=X&ved=1t:155783&ictx=111",
        price: 89,
        favourite: false,
        description: "The National Zoo is a Malaysian zoo located on 110 acres of land in Ulu Klang, Gombak District, Selangor, Malaysia. It was officially opened on November 14, 1963, by the country's first prime minister, Tunku Abdul Rahman.",
        operating_hour: "10:00 AM - 10:00 PM"
    },

    'bukit tabur': {
        category: "destination",
        link_name: "bukit tabur",
        name: "Bukit Tabur",
        image: "/bukit-tabur.jpg",
        idea: "Green Lifestyle Enthusiasts",
        duration: "1 Days",
        rating: "4.9",
        short_location: "Kuala Lumpur",
        location: "53100, Selangor",
        location_link: "https://www.google.com/maps/place/Bukit+Tabur/@3.2347219,101.747778,15z/data=!3m1!4b1!4m6!3m5!1s0x31cc38fc1e795d7d:0x330ab557cd2fc26c!8m2!3d3.234722!4d101.747778!16s%2Fg%2F11bc5tgndv?entry=ttu&g_ep=EgoyMDI1MDUyOC4wIKXMDSoASAFQAw%3D%3D",
        price: 30,
        favourite: false,
        description: "Bukit Tabur, meaning Spread Rock Hill in Malay, is a prominent geological formation in Malaysia, specifically a quartz ridge, known for its challenging but rewarding hikes and stunning views. It's a popular destination for both local and international hikers, offering a mix of difficult terrain and panoramic vistas.",
        operating_hour: "10:00 AM - 10:00 PM"
    },

    'thean hou temple': {
        category: "destination",
        link_name: "thean hou temple",
        name: "Thean Hou Temple",
        image: "/thean-hou-temple.jpg",
        idea: "Cultural Lover",
        duration: "1 Days",
        rating: "4.9",
        short_location: "Kuala Lumpur",
        location: "65 Persiaran Endah Off Jalan Syed Putra, Kuala Lumpur 50460 Malaysia",
        location_link: "https://www.tripadvisor.com.my/Attraction_Review-g298570-d457134-Reviews-Thean_Hou_Temple-Kuala_Lumpur_Wilayah_Persekutuan.html#:~:text=65%20Persiaran%20Endah%20Off%20Jalan%20Syed%20Putra%2C%20Kuala%20Lumpur%2050460%20Malaysia",
        price: 39,
        favourite: false,
        description: "This ornate Chinese temple dedicated to the Queen of Heaven, Thean Hou, protectorate of people who make their living from the sea. The temple borrows from Buddhist, Taoist and Confucian traditions. Some visitors believe the panoramic views of KL alone make the trip up the hill worthwhile.",
        operating_hour: "10:00 AM - 5:30 PM"
    },

    'red square': {
        category: "destination",
        link_name: "red square",
        name: "Red Square",
        image: "/show-case-2.png",
        idea: "History Buffs",
        duration: "2 Days",
        rating: "4.9",
        short_location: "Melaka",
        location: "Bandar Hilir, 75200 Malacca",
        location_link: "https://www.google.com/maps/place/melaka+red+square/data=!4m2!3m1!1s0x31d1f1ddd411e8fb:0x564481a2e0e143f5?sa=X&ved=1t:155783&ictx=111",
        price: 159,
        favourite: false,
        description: "Historic square featuring maroon-colored structures in the Dutch colonial style.",
        operating_hour: "10:00 AM - 9:30 PM"
    },

    'encore melaka': {
        category: "destination",
        link_name: "encore melaka",
        name: "Encore Melaka",
        image: "/encore-melaka.jpg",
        idea: "Curious learners",
        duration: "2 Days",
        rating: "4.9",
        short_location: "Melaka",
        location: "No. 3 Jalan KSB Impression 8, Impression City at Kota Syahbandar, Melaka 75200 Malaysia",
        location_link: "https://www.google.com/maps/place/encore+melaka+location/data=!4m2!3m1!1s0x31d1f197bc36a73f:0x7cff815fe2da766c?sa=X&ved=1t:242&ictx=111",
        price: 159,
        favourite: false,
        description: "A cultural performance not to be missed ENCORE MELAKA is an immersive performance with a series of untold stories of Melaka, which reflects a society that embraces diversity and inclusiveness. This 70-minutes long mega show reminiscing life stories of the locals with state-of-the-art production sets. The audience will experience 360-degree rotating audience platform fronting a 240-meter long stage, multi-lifting platforms, sound & light and a 3D mapping projection that creates virtual reality that travels through time.",
        operating_hour: "11:00 AM - 10:30 PM"
    },

    'melaka straits mosque': {
        category: "destination",
        link_name: "melaka straits mosque",
        name: "Melaka Straits Mosque",
        image: "/straits-of-malacca-mosque.jpg",
        idea: "Cultural Lover",
        duration: "1 Days",
        rating: "4.9",
        short_location: "Melaka",
        location: "Masjid Selat, 75000, Melaka",
        location_link: "https://www.google.com/maps/dir//Masjid+Selat,+75000,+Melaka/@2.1790775,102.1667329,12z/data=!4m8!4m7!1m0!1m5!1m1!1s0x31d1f1db5a5920d9:0xd9cf83e66b327038!2m2!1d102.2491797!2d2.1791849?entry=ttu&g_ep=EgoyMDI1MDYwNC4wIKXMDSoASAFQAw%3D%3D",
        price: 59,
        favourite: false,
        description: "The Malacca Straits Mosque is a mosque located on the artificial Malacca Island in Malacca City, Malaysia. Constructed at a cost of about MYR10 million, it was inaugurated on 24 November 2006 by the King of Malaysia, Tuanku Syed Sirajuddin ibni Almarhum Tuanku Syed Putra Jamalullail.",
        operating_hour: "9:00 AM - 8:00 PM"
    },

    'baba house melaka': {
        category: "destination",
        link_name: "baba house melaka",
        name: "Baba House Melaka",
        image: "/baba-house-melaka.jpg",
        idea: "Cultural Lover",
        duration: "1 Days",
        rating: "4.2",
        short_location: "Melaka",
        location: "Taman Kota Laksamana, 75200 Melaka",
        location_link: "https://www.google.com/maps?gs_lcrp=EgZjaHJvbWUqEggAEAAYFBiHAhjjAhixAxiABDISCAAQABgUGIcCGOMCGLEDGIAEMhsIARAuGBQYrwEYxwEYhwIYsQMYgAQYmAUYmQUyBwgCEAAYgAQyBwgDEAAYgAQyBwgEEAAYgAQyBwgFEAAYgAQyBwgGEAAYgAQyBggHEEUYPKgCALACAA&um=1&ie=UTF-8&fb=1&gl=my&sa=X&geocode=KX9XuJfc8dExMevkcnyFe38w&daddr=121-127,+Jalan+Tun+Tan+Cheng+Lock,+Taman+Kota+Laksamana,+75200+Melaka",
        price: 40,
        favourite: false,
        description: "Baba House Melaka is celebrated for combining traditional Peranakan charm with modern comforts, creating an inviting atmosphere that resonates with travelers. While guests commend the cleanliness and the service for enhancing their stay, some highlight concerns with room soundproofing and inconsistent housekeeping.",
        operating_hour: "9:00 AM - 8:00 PM"
    },

    'mount kinabalu': {
        category: "destination",
        link_name: "mount kinabalu",
        name: "Mount Kinabalu",
        image: "/mount-kinabalu.jpg",
        idea: "Green Lifestyle Enthusiasts",
        duration: "3 Days",
        rating: "4.9",
        short_location: "Sabah",
        location: "Ranau, Sabah",
        location_link: "https://www.google.com/maps/place/Mount+Kinabalu/@6.075313,116.5588237,15z/data=!3m1!4b1!4m6!3m5!1s0x323ba2565e9224cb:0x2281c3fec0a9c05e!8m2!3d6.0753131!4d116.5588237!16zL20vMHFxbWY?entry=ttu&g_ep=EgoyMDI1MDYxNy4wIKXMDSoASAFQAw%3D%3D",
        price: 190,
        favourite: false,
        description: "Mount Kinabalu is the highest mountain in Malaysia and Borneo. With a height of 4,095 metres, it is the third-highest peak of an island on Earth, the 28th highest peak in Southeast Asia, and 20th most prominent mountain in the world. The mountain is located in Ranau district, West Coast Division of Sabah, Malaysia. ",
        operating_hour: "10:00 AM - 7:00 PM"
    },

    'turtle island park': {
        category: "destination",
        link_name: "turtle island park",
        name: "Turtle Island Park",
        image: "/turtle-island-park.jpg",
        idea: "Green Lifestyle Enthusiasts",
        duration: "3 Days",
        rating: "4.9",
        short_location: "Sabah",
        location: "Ranau, Sabah",
        location_link: "https://www.google.com/maps/place/Turtle+Islands+Park/@6.1503861,118.0539499,17z/data=!4m6!3m5!1s0x3238fa450c02319d:0x2b41d94e053b887d!8m2!3d6.1494474!4d118.0540786!16zL20vMDdkMWh3?entry=ttu&g_ep=EgoyMDI1MDYxNy4wIKXMDSoASAFQAw%3D%3D",
        price: 110,
        favourite: false,
        description: "Turtle Islands Park is located within the Turtle Islands, which lie in the Sulu Sea some 3 kilometres north of Sandakan in Sabah, Malaysia. It consists of 3 islands - Selingaan, Little Bakkungan and Gulisaan, including the surrounding coral reefs and ocean",
        operating_hour: "6:00 AM - 12:00 PM"
    },

    'labuk monkey bay': {
        category: "destination",
        link_name: "labuk monkey bay",
        name: "Labuk Monkey Bay",
        image: "/labuk-monkey-bay.jpg",
        idea: "Curious learners",
        duration: "1 Days",
        rating: "4.9",
        short_location: "Sabah",
        location: "Jalan Labuk, 90000 Sandakan, Sabah",
        location_link: "https://www.google.com/maps/place/Mount+Kinabalu/@6.075313,116.5588237,15z/data=!3m1!4b1!4m6!3m5!1s0x323ba2565e9224cb:0x2281c3fec0a9c05e!8m2!3d6.0753131!4d116.5588237!16zL20vMHFxbWY?entry=ttu&g_ep=EgoyMDI1MDYxNy4wIKXMDSoASAFQAw%3D%3D",
        price: 39,
        favourite: false,
        description: "Hundreds of wild monkeys roam freely at this expansive sanctuary with popular scheduled feedings.",
        operating_hour: "8:00 AM - 7:00 PM"
    }

};


module.exports = destinations;